INSERT INTO city (name, province_id) VALUES ('MANILA', '1');
INSERT INTO city (name, province_id) VALUES ('CITY OF MAKATI', '1');
INSERT INTO city (name, province_id) VALUES ('CITY OF MUNTINLUPA', '1');
INSERT INTO city (name, province_id) VALUES ('CITY OF PARAÑAQUE', '1');
INSERT INTO city (name, province_id) VALUES ('PASAY CITY', '1');
INSERT INTO city (name, province_id) VALUES ('PATEROS', '1');
INSERT INTO city (name, province_id) VALUES ('TAGUIG CITY', '1');
INSERT INTO city (name, province_id) VALUES ('CITY OF MARIKINA', '1');
INSERT INTO city (name, province_id) VALUES ('CITY OF PASIG', '1');
INSERT INTO city (name, province_id) VALUES ('QUEZON CITY', '1');
INSERT INTO city (name, province_id) VALUES ('CITY OF SAN JUAN', '1');
INSERT INTO city (name, province_id) VALUES ('CITY OF MALABON', '1');
INSERT INTO city (name, province_id) VALUES ('CITY OF NAVOTAS', '1');
INSERT INTO city (name, province_id) VALUES ('CITY OF VALENZUELA', '1');
INSERT INTO city (name, province_id) VALUES ('CITY OF LAS PIÑAS', '1');
INSERT INTO city (name, province_id) VALUES ('CITY OF MANDALUYONG', '1');
INSERT INTO city (name, province_id) VALUES ('CALOOCAN CITY', '1');
INSERT INTO city (name, province_id) VALUES ('BOLINEY', '2');
INSERT INTO city (name, province_id) VALUES ('BUCAY', '2');
INSERT INTO city (name, province_id) VALUES ('BUCLOC', '2');
INSERT INTO city (name, province_id) VALUES ('DAGUIOMAN', '2');
INSERT INTO city (name, province_id) VALUES ('DANGLAS', '2');
INSERT INTO city (name, province_id) VALUES ('DOLORES', '2');
INSERT INTO city (name, province_id) VALUES ('LA PAZ', '2');
INSERT INTO city (name, province_id) VALUES ('LACUB', '2');
INSERT INTO city (name, province_id) VALUES ('LAGANGILANG', '2');
INSERT INTO city (name, province_id) VALUES ('LAGAYAN', '2');
INSERT INTO city (name, province_id) VALUES ('LANGIDEN', '2');
INSERT INTO city (name, province_id) VALUES ('LICUAN-BAAY (LICUAN)', '2');
INSERT INTO city (name, province_id) VALUES ('LUBA', '2');
INSERT INTO city (name, province_id) VALUES ('MALIBCONG', '2');
INSERT INTO city (name, province_id) VALUES ('MANABO', '2');
INSERT INTO city (name, province_id) VALUES ('PEÑARRUBIA', '2');
INSERT INTO city (name, province_id) VALUES ('PIDIGAN', '2');
INSERT INTO city (name, province_id) VALUES ('PILAR', '2');
INSERT INTO city (name, province_id) VALUES ('SALLAPADAN', '2');
INSERT INTO city (name, province_id) VALUES ('SAN ISIDRO', '2');
INSERT INTO city (name, province_id) VALUES ('SAN JUAN', '2');
INSERT INTO city (name, province_id) VALUES ('SAN QUINTIN', '2');
INSERT INTO city (name, province_id) VALUES ('TAYUM', '2');
INSERT INTO city (name, province_id) VALUES ('TINEG', '2');
INSERT INTO city (name, province_id) VALUES ('TUBO', '2');
INSERT INTO city (name, province_id) VALUES ('VILLAVICIOSA', '2');
INSERT INTO city (name, province_id) VALUES ('CONNER', '3');
INSERT INTO city (name, province_id) VALUES ('FLORA', '3');
INSERT INTO city (name, province_id) VALUES ('KABUGAO (Capital)', '3');
INSERT INTO city (name, province_id) VALUES ('LUNA', '3');
INSERT INTO city (name, province_id) VALUES ('PUDTOL', '3');
INSERT INTO city (name, province_id) VALUES ('SANTA MARCELA', '3');
INSERT INTO city (name, province_id) VALUES ('BAGUIO CITY', '4');
INSERT INTO city (name, province_id) VALUES ('BAKUN', '4');
INSERT INTO city (name, province_id) VALUES ('BOKOD', '4');
INSERT INTO city (name, province_id) VALUES ('BUGUIAS', '4');
INSERT INTO city (name, province_id) VALUES ('ITOGON', '4');
INSERT INTO city (name, province_id) VALUES ('KABAYAN', '4');
INSERT INTO city (name, province_id) VALUES ('KAPANGAN', '4');
INSERT INTO city (name, province_id) VALUES ('KIBUNGAN', '4');
INSERT INTO city (name, province_id) VALUES ('LA TRINIDAD (Capital)', '4');
INSERT INTO city (name, province_id) VALUES ('MANKAYAN', '4');
INSERT INTO city (name, province_id) VALUES ('SABLAN', '4');
INSERT INTO city (name, province_id) VALUES ('TUBA', '4');
INSERT INTO city (name, province_id) VALUES ('TUBLAY', '4');
INSERT INTO city (name, province_id) VALUES ('HUNGDUAN', '5');
INSERT INTO city (name, province_id) VALUES ('KIANGAN', '5');
INSERT INTO city (name, province_id) VALUES ('LAGAWE (Capital)', '5');
INSERT INTO city (name, province_id) VALUES ('LAMUT', '5');
INSERT INTO city (name, province_id) VALUES ('MAYOYAO', '5');
INSERT INTO city (name, province_id) VALUES ('ALFONSO LISTA (POTIA)', '5');
INSERT INTO city (name, province_id) VALUES ('AGUINALDO', '5');
INSERT INTO city (name, province_id) VALUES ('HINGYON', '5');
INSERT INTO city (name, province_id) VALUES ('TINOC', '5');
INSERT INTO city (name, province_id) VALUES ('ASIPULO', '5');
INSERT INTO city (name, province_id) VALUES ('LUBUAGAN', '6');
INSERT INTO city (name, province_id) VALUES ('PASIL', '6');
INSERT INTO city (name, province_id) VALUES ('PINUKPUK', '6');
INSERT INTO city (name, province_id) VALUES ('RIZAL (LIWAN)', '6');
INSERT INTO city (name, province_id) VALUES ('CITY OF TABUK (Capital)', '6');
INSERT INTO city (name, province_id) VALUES ('TANUDAN', '6');
INSERT INTO city (name, province_id) VALUES ('TINGLAYAN', '6');
INSERT INTO city (name, province_id) VALUES ('BAUKO', '7');
INSERT INTO city (name, province_id) VALUES ('BESAO', '7');
INSERT INTO city (name, province_id) VALUES ('BONTOC (Capital)', '7');
INSERT INTO city (name, province_id) VALUES ('NATONIN', '7');
INSERT INTO city (name, province_id) VALUES ('PARACELIS', '7');
INSERT INTO city (name, province_id) VALUES ('SABANGAN', '7');
INSERT INTO city (name, province_id) VALUES ('SADANGA', '7');
INSERT INTO city (name, province_id) VALUES ('SAGADA', '7');
INSERT INTO city (name, province_id) VALUES ('TADIAN', '7');
INSERT INTO city (name, province_id) VALUES ('BANGUED (Capital)', '2');
INSERT INTO city (name, province_id) VALUES ('CALANASAN (BAYAG)', '3');
INSERT INTO city (name, province_id) VALUES ('ATOK', '4');
INSERT INTO city (name, province_id) VALUES ('BANAUE', '5');
INSERT INTO city (name, province_id) VALUES ('BALBALAN', '6');
INSERT INTO city (name, province_id) VALUES ('BARLIG', '7');
INSERT INTO city (name, province_id) VALUES ('BACARRA', '8');
INSERT INTO city (name, province_id) VALUES ('BADOC', '8');
INSERT INTO city (name, province_id) VALUES ('BANGUI', '8');
INSERT INTO city (name, province_id) VALUES ('CITY OF BATAC', '8');
INSERT INTO city (name, province_id) VALUES ('BURGOS', '8');
INSERT INTO city (name, province_id) VALUES ('CARASI', '8');
INSERT INTO city (name, province_id) VALUES ('CURRIMAO', '8');
INSERT INTO city (name, province_id) VALUES ('DINGRAS', '8');
INSERT INTO city (name, province_id) VALUES ('DUMALNEG', '8');
INSERT INTO city (name, province_id) VALUES ('BANNA (ESPIRITU)', '8');
INSERT INTO city (name, province_id) VALUES ('LAOAG CITY (Capital)', '8');
INSERT INTO city (name, province_id) VALUES ('MARCOS', '8');
INSERT INTO city (name, province_id) VALUES ('NUEVA ERA', '8');
INSERT INTO city (name, province_id) VALUES ('PAGUDPUD', '8');
INSERT INTO city (name, province_id) VALUES ('PAOAY', '8');
INSERT INTO city (name, province_id) VALUES ('PASUQUIN', '8');
INSERT INTO city (name, province_id) VALUES ('PIDDIG', '8');
INSERT INTO city (name, province_id) VALUES ('PINILI', '8');
INSERT INTO city (name, province_id) VALUES ('SAN NICOLAS', '8');
INSERT INTO city (name, province_id) VALUES ('SARRAT', '8');
INSERT INTO city (name, province_id) VALUES ('SOLSONA', '8');
INSERT INTO city (name, province_id) VALUES ('VINTAR', '8');
INSERT INTO city (name, province_id) VALUES ('BANAYOYO', '9');
INSERT INTO city (name, province_id) VALUES ('BANTAY', '9');
INSERT INTO city (name, province_id) VALUES ('CABUGAO', '9');
INSERT INTO city (name, province_id) VALUES ('CITY OF CANDON', '9');
INSERT INTO city (name, province_id) VALUES ('CAOAYAN', '9');
INSERT INTO city (name, province_id) VALUES ('CERVANTES', '9');
INSERT INTO city (name, province_id) VALUES ('GALIMUYOD', '9');
INSERT INTO city (name, province_id) VALUES ('GREGORIO DEL PILAR (CONCEPCION)', '9');
INSERT INTO city (name, province_id) VALUES ('LIDLIDDA', '9');
INSERT INTO city (name, province_id) VALUES ('MAGSINGAL', '9');
INSERT INTO city (name, province_id) VALUES ('NAGBUKEL', '9');
INSERT INTO city (name, province_id) VALUES ('NARVACAN', '9');
INSERT INTO city (name, province_id) VALUES ('QUIRINO (ANGKAKI)', '9');
INSERT INTO city (name, province_id) VALUES ('SALCEDO (BAUGEN)', '9');
INSERT INTO city (name, province_id) VALUES ('SAN EMILIO', '9');
INSERT INTO city (name, province_id) VALUES ('SAN ESTEBAN', '9');
INSERT INTO city (name, province_id) VALUES ('SAN ILDEFONSO', '9');
INSERT INTO city (name, province_id) VALUES ('SAN JUAN (LAPOG)', '9');
INSERT INTO city (name, province_id) VALUES ('SAN VICENTE', '9');
INSERT INTO city (name, province_id) VALUES ('SANTA', '9');
INSERT INTO city (name, province_id) VALUES ('SANTA CATALINA', '9');
INSERT INTO city (name, province_id) VALUES ('SANTA CRUZ', '9');
INSERT INTO city (name, province_id) VALUES ('SANTA LUCIA', '9');
INSERT INTO city (name, province_id) VALUES ('SANTA MARIA', '9');
INSERT INTO city (name, province_id) VALUES ('SANTIAGO', '9');
INSERT INTO city (name, province_id) VALUES ('SANTO DOMINGO', '9');
INSERT INTO city (name, province_id) VALUES ('SIGAY', '9');
INSERT INTO city (name, province_id) VALUES ('SINAIT', '9');
INSERT INTO city (name, province_id) VALUES ('SUGPON', '9');
INSERT INTO city (name, province_id) VALUES ('SUYO', '9');
INSERT INTO city (name, province_id) VALUES ('TAGUDIN', '9');
INSERT INTO city (name, province_id) VALUES ('CITY OF VIGAN (Capital)', '9');
INSERT INTO city (name, province_id) VALUES ('ARINGAY', '10');
INSERT INTO city (name, province_id) VALUES ('BACNOTAN', '10');
INSERT INTO city (name, province_id) VALUES ('BAGULIN', '10');
INSERT INTO city (name, province_id) VALUES ('BALAOAN', '10');
INSERT INTO city (name, province_id) VALUES ('BANGAR', '10');
INSERT INTO city (name, province_id) VALUES ('BAUANG', '10');
INSERT INTO city (name, province_id) VALUES ('CABA', '10');
INSERT INTO city (name, province_id) VALUES ('NAGUILIAN', '10');
INSERT INTO city (name, province_id) VALUES ('PUGO', '10');
INSERT INTO city (name, province_id) VALUES ('ROSARIO', '10');
INSERT INTO city (name, province_id) VALUES ('CITY OF SAN FERNANDO (Capital)', '10');
INSERT INTO city (name, province_id) VALUES ('SAN GABRIEL', '10');
INSERT INTO city (name, province_id) VALUES ('SANTO TOMAS', '10');
INSERT INTO city (name, province_id) VALUES ('SANTOL', '10');
INSERT INTO city (name, province_id) VALUES ('SUDIPEN', '10');
INSERT INTO city (name, province_id) VALUES ('TUBAO', '10');
INSERT INTO city (name, province_id) VALUES ('AGUILAR', '11');
INSERT INTO city (name, province_id) VALUES ('CITY OF ALAMINOS', '11');
INSERT INTO city (name, province_id) VALUES ('ALCALA', '11');
INSERT INTO city (name, province_id) VALUES ('ANDA', '11');
INSERT INTO city (name, province_id) VALUES ('ASINGAN', '11');
INSERT INTO city (name, province_id) VALUES ('BALUNGAO', '11');
INSERT INTO city (name, province_id) VALUES ('BANI', '11');
INSERT INTO city (name, province_id) VALUES ('BASISTA', '11');
INSERT INTO city (name, province_id) VALUES ('BAUTISTA', '11');
INSERT INTO city (name, province_id) VALUES ('BAYAMBANG', '11');
INSERT INTO city (name, province_id) VALUES ('BINALONAN', '11');
INSERT INTO city (name, province_id) VALUES ('BINMALEY', '11');
INSERT INTO city (name, province_id) VALUES ('BOLINAO', '11');
INSERT INTO city (name, province_id) VALUES ('BUGALLON', '11');
INSERT INTO city (name, province_id) VALUES ('CALASIAO', '11');
INSERT INTO city (name, province_id) VALUES ('DAGUPAN CITY', '11');
INSERT INTO city (name, province_id) VALUES ('DASOL', '11');
INSERT INTO city (name, province_id) VALUES ('INFANTA', '11');
INSERT INTO city (name, province_id) VALUES ('LABRADOR', '11');
INSERT INTO city (name, province_id) VALUES ('LINGAYEN (Capital)', '11');
INSERT INTO city (name, province_id) VALUES ('MABINI', '11');
INSERT INTO city (name, province_id) VALUES ('MALASIQUI', '11');
INSERT INTO city (name, province_id) VALUES ('MANAOAG', '11');
INSERT INTO city (name, province_id) VALUES ('MANGALDAN', '11');
INSERT INTO city (name, province_id) VALUES ('MANGATAREM', '11');
INSERT INTO city (name, province_id) VALUES ('MAPANDAN', '11');
INSERT INTO city (name, province_id) VALUES ('NATIVIDAD', '11');
INSERT INTO city (name, province_id) VALUES ('POZORRUBIO', '11');
INSERT INTO city (name, province_id) VALUES ('ROSALES', '11');
INSERT INTO city (name, province_id) VALUES ('SAN CARLOS CITY', '11');
INSERT INTO city (name, province_id) VALUES ('SAN FABIAN', '11');
INSERT INTO city (name, province_id) VALUES ('SAN JACINTO', '11');
INSERT INTO city (name, province_id) VALUES ('SAN MANUEL', '11');
INSERT INTO city (name, province_id) VALUES ('SANTA BARBARA', '11');
INSERT INTO city (name, province_id) VALUES ('SISON', '11');
INSERT INTO city (name, province_id) VALUES ('SUAL', '11');
INSERT INTO city (name, province_id) VALUES ('TAYUG', '11');
INSERT INTO city (name, province_id) VALUES ('UMINGAN', '11');
INSERT INTO city (name, province_id) VALUES ('URBIZTONDO', '11');
INSERT INTO city (name, province_id) VALUES ('CITY OF URDANETA', '11');
INSERT INTO city (name, province_id) VALUES ('VILLASIS', '11');
INSERT INTO city (name, province_id) VALUES ('LAOAC', '11');
INSERT INTO city (name, province_id) VALUES ('ADAMS', '8');
INSERT INTO city (name, province_id) VALUES ('ALILEM', '9');
INSERT INTO city (name, province_id) VALUES ('AGOO', '10');
INSERT INTO city (name, province_id) VALUES ('AGNO', '11');
INSERT INTO city (name, province_id) VALUES ('ITBAYAT', '12');
INSERT INTO city (name, province_id) VALUES ('IVANA', '12');
INSERT INTO city (name, province_id) VALUES ('MAHATAO', '12');
INSERT INTO city (name, province_id) VALUES ('SABTANG', '12');
INSERT INTO city (name, province_id) VALUES ('UYUGAN', '12');
INSERT INTO city (name, province_id) VALUES ('ALLACAPAN', '13');
INSERT INTO city (name, province_id) VALUES ('AMULUNG', '13');
INSERT INTO city (name, province_id) VALUES ('APARRI', '13');
INSERT INTO city (name, province_id) VALUES ('BAGGAO', '13');
INSERT INTO city (name, province_id) VALUES ('BALLESTEROS', '13');
INSERT INTO city (name, province_id) VALUES ('BUGUEY', '13');
INSERT INTO city (name, province_id) VALUES ('CALAYAN', '13');
INSERT INTO city (name, province_id) VALUES ('CAMALANIUGAN', '13');
INSERT INTO city (name, province_id) VALUES ('CLAVERIA', '13');
INSERT INTO city (name, province_id) VALUES ('ENRILE', '13');
INSERT INTO city (name, province_id) VALUES ('GATTARAN', '13');
INSERT INTO city (name, province_id) VALUES ('GONZAGA', '13');
INSERT INTO city (name, province_id) VALUES ('IGUIG', '13');
INSERT INTO city (name, province_id) VALUES ('LAL-LO', '13');
INSERT INTO city (name, province_id) VALUES ('LASAM', '13');
INSERT INTO city (name, province_id) VALUES ('PAMPLONA', '13');
INSERT INTO city (name, province_id) VALUES ('PEÑABLANCA', '13');
INSERT INTO city (name, province_id) VALUES ('PIAT', '13');
INSERT INTO city (name, province_id) VALUES ('RIZAL', '13');
INSERT INTO city (name, province_id) VALUES ('SANCHEZ-MIRA', '13');
INSERT INTO city (name, province_id) VALUES ('SANTA ANA', '13');
INSERT INTO city (name, province_id) VALUES ('SANTA PRAXEDES', '13');
INSERT INTO city (name, province_id) VALUES ('SANTA TERESITA', '13');
INSERT INTO city (name, province_id) VALUES ('SANTO NIÑO (FAIRE)', '13');
INSERT INTO city (name, province_id) VALUES ('SOLANA', '13');
INSERT INTO city (name, province_id) VALUES ('TUAO', '13');
INSERT INTO city (name, province_id) VALUES ('TUGUEGARAO CITY (Capital)', '13');
INSERT INTO city (name, province_id) VALUES ('ANGADANAN', '14');
INSERT INTO city (name, province_id) VALUES ('AURORA', '14');
INSERT INTO city (name, province_id) VALUES ('BENITO SOLIVEN', '14');
INSERT INTO city (name, province_id) VALUES ('CABAGAN', '14');
INSERT INTO city (name, province_id) VALUES ('CABATUAN', '14');
INSERT INTO city (name, province_id) VALUES ('CITY OF CAUAYAN', '14');
INSERT INTO city (name, province_id) VALUES ('CORDON', '14');
INSERT INTO city (name, province_id) VALUES ('DINAPIGUE', '14');
INSERT INTO city (name, province_id) VALUES ('DIVILACAN', '14');
INSERT INTO city (name, province_id) VALUES ('ECHAGUE', '14');
INSERT INTO city (name, province_id) VALUES ('GAMU', '14');
INSERT INTO city (name, province_id) VALUES ('ILAGAN (Capital)', '14');
INSERT INTO city (name, province_id) VALUES ('JONES', '14');
INSERT INTO city (name, province_id) VALUES ('MACONACON', '14');
INSERT INTO city (name, province_id) VALUES ('DELFIN ALBANO (MAGSAYSAY)', '14');
INSERT INTO city (name, province_id) VALUES ('MALLIG', '14');
INSERT INTO city (name, province_id) VALUES ('PALANAN', '14');
INSERT INTO city (name, province_id) VALUES ('QUEZON', '14');
INSERT INTO city (name, province_id) VALUES ('QUIRINO', '14');
INSERT INTO city (name, province_id) VALUES ('RAMON', '14');
INSERT INTO city (name, province_id) VALUES ('REINA MERCEDES', '14');
INSERT INTO city (name, province_id) VALUES ('ROXAS', '14');
INSERT INTO city (name, province_id) VALUES ('SAN AGUSTIN', '14');
INSERT INTO city (name, province_id) VALUES ('SAN GUILLERMO', '14');
INSERT INTO city (name, province_id) VALUES ('SAN MARIANO', '14');
INSERT INTO city (name, province_id) VALUES ('SAN MATEO', '14');
INSERT INTO city (name, province_id) VALUES ('SAN PABLO', '14');
INSERT INTO city (name, province_id) VALUES ('CITY OF SANTIAGO', '14');
INSERT INTO city (name, province_id) VALUES ('TUMAUINI', '14');
INSERT INTO city (name, province_id) VALUES ('ARITAO', '15');
INSERT INTO city (name, province_id) VALUES ('BAGABAG', '15');
INSERT INTO city (name, province_id) VALUES ('BAMBANG', '15');
INSERT INTO city (name, province_id) VALUES ('BAYOMBONG (Capital)', '15');
INSERT INTO city (name, province_id) VALUES ('DIADI', '15');
INSERT INTO city (name, province_id) VALUES ('DUPAX DEL NORTE', '15');
INSERT INTO city (name, province_id) VALUES ('DUPAX DEL SUR', '15');
INSERT INTO city (name, province_id) VALUES ('KASIBU', '15');
INSERT INTO city (name, province_id) VALUES ('KAYAPA', '15');
INSERT INTO city (name, province_id) VALUES ('SANTA FE', '15');
INSERT INTO city (name, province_id) VALUES ('SOLANO', '15');
INSERT INTO city (name, province_id) VALUES ('VILLAVERDE', '15');
INSERT INTO city (name, province_id) VALUES ('ALFONSO CASTANEDA', '15');
INSERT INTO city (name, province_id) VALUES ('CABARROGUIS (Capital)', '16');
INSERT INTO city (name, province_id) VALUES ('DIFFUN', '16');
INSERT INTO city (name, province_id) VALUES ('MADDELA', '16');
INSERT INTO city (name, province_id) VALUES ('SAGUDAY', '16');
INSERT INTO city (name, province_id) VALUES ('NAGTIPUNAN', '16');
INSERT INTO city (name, province_id) VALUES ('BASCO (Capital)', '12');
INSERT INTO city (name, province_id) VALUES ('ABULUG', '13');
INSERT INTO city (name, province_id) VALUES ('ALICIA', '14');
INSERT INTO city (name, province_id) VALUES ('AMBAGUIO', '15');
INSERT INTO city (name, province_id) VALUES ('AGLIPAY', '16');
INSERT INTO city (name, province_id) VALUES ('CASIGURAN', '17');
INSERT INTO city (name, province_id) VALUES ('DILASAG', '17');
INSERT INTO city (name, province_id) VALUES ('DINALUNGAN', '17');
INSERT INTO city (name, province_id) VALUES ('DINGALAN', '17');
INSERT INTO city (name, province_id) VALUES ('DIPACULAO', '17');
INSERT INTO city (name, province_id) VALUES ('MARIA AURORA', '17');
INSERT INTO city (name, province_id) VALUES ('SAN LUIS', '17');
INSERT INTO city (name, province_id) VALUES ('BAGAC', '18');
INSERT INTO city (name, province_id) VALUES ('CITY OF BALANGA (Capital)', '18');
INSERT INTO city (name, province_id) VALUES ('DINALUPIHAN', '18');
INSERT INTO city (name, province_id) VALUES ('HERMOSA', '18');
INSERT INTO city (name, province_id) VALUES ('LIMAY', '18');
INSERT INTO city (name, province_id) VALUES ('MARIVELES', '18');
INSERT INTO city (name, province_id) VALUES ('MORONG', '18');
INSERT INTO city (name, province_id) VALUES ('ORANI', '18');
INSERT INTO city (name, province_id) VALUES ('ORION', '18');
INSERT INTO city (name, province_id) VALUES ('SAMAL', '18');
INSERT INTO city (name, province_id) VALUES ('BALAGTAS (BIGAA)', '19');
INSERT INTO city (name, province_id) VALUES ('BALIUAG', '19');
INSERT INTO city (name, province_id) VALUES ('BOCAUE', '19');
INSERT INTO city (name, province_id) VALUES ('BULACAN', '19');
INSERT INTO city (name, province_id) VALUES ('BUSTOS', '19');
INSERT INTO city (name, province_id) VALUES ('CALUMPIT', '19');
INSERT INTO city (name, province_id) VALUES ('GUIGUINTO', '19');
INSERT INTO city (name, province_id) VALUES ('HAGONOY', '19');
INSERT INTO city (name, province_id) VALUES ('CITY OF MALOLOS (Capital)', '19');
INSERT INTO city (name, province_id) VALUES ('MARILAO', '19');
INSERT INTO city (name, province_id) VALUES ('CITY OF MEYCAUAYAN', '19');
INSERT INTO city (name, province_id) VALUES ('NORZAGARAY', '19');
INSERT INTO city (name, province_id) VALUES ('OBANDO', '19');
INSERT INTO city (name, province_id) VALUES ('PANDI', '19');
INSERT INTO city (name, province_id) VALUES ('PAOMBONG', '19');
INSERT INTO city (name, province_id) VALUES ('PLARIDEL', '19');
INSERT INTO city (name, province_id) VALUES ('PULILAN', '19');
INSERT INTO city (name, province_id) VALUES ('CITY OF SAN JOSE DEL MONTE', '19');
INSERT INTO city (name, province_id) VALUES ('SAN MIGUEL', '19');
INSERT INTO city (name, province_id) VALUES ('SAN RAFAEL', '19');
INSERT INTO city (name, province_id) VALUES ('DOÑA REMEDIOS TRINIDAD', '19');
INSERT INTO city (name, province_id) VALUES ('BONGABON', '20');
INSERT INTO city (name, province_id) VALUES ('CABANATUAN CITY', '20');
INSERT INTO city (name, province_id) VALUES ('CABIAO', '20');
INSERT INTO city (name, province_id) VALUES ('CARRANGLAN', '20');
INSERT INTO city (name, province_id) VALUES ('CUYAPO', '20');
INSERT INTO city (name, province_id) VALUES ('GABALDON (BITULOK & SABANI)', '20');
INSERT INTO city (name, province_id) VALUES ('CITY OF GAPAN', '20');
INSERT INTO city (name, province_id) VALUES ('GENERAL MAMERTO NATIVIDAD', '20');
INSERT INTO city (name, province_id) VALUES ('GENERAL TINIO (PAPAYA)', '20');
INSERT INTO city (name, province_id) VALUES ('GUIMBA', '20');
INSERT INTO city (name, province_id) VALUES ('JAEN', '20');
INSERT INTO city (name, province_id) VALUES ('LAUR', '20');
INSERT INTO city (name, province_id) VALUES ('LICAB', '20');
INSERT INTO city (name, province_id) VALUES ('LLANERA', '20');
INSERT INTO city (name, province_id) VALUES ('LUPAO', '20');
INSERT INTO city (name, province_id) VALUES ('SCIENCE CITY OF MUÑOZ', '20');
INSERT INTO city (name, province_id) VALUES ('NAMPICUAN', '20');
INSERT INTO city (name, province_id) VALUES ('PALAYAN CITY (Capital)', '20');
INSERT INTO city (name, province_id) VALUES ('PANTABANGAN', '20');
INSERT INTO city (name, province_id) VALUES ('PEÑARANDA', '20');
INSERT INTO city (name, province_id) VALUES ('SAN ANTONIO', '20');
INSERT INTO city (name, province_id) VALUES ('SAN JOSE CITY', '20');
INSERT INTO city (name, province_id) VALUES ('SAN LEONARDO', '20');
INSERT INTO city (name, province_id) VALUES ('SANTA ROSA', '20');
INSERT INTO city (name, province_id) VALUES ('TALAVERA', '20');
INSERT INTO city (name, province_id) VALUES ('TALUGTUG', '20');
INSERT INTO city (name, province_id) VALUES ('ZARAGOZA', '20');
INSERT INTO city (name, province_id) VALUES ('APALIT', '21');
INSERT INTO city (name, province_id) VALUES ('ARAYAT', '21');
INSERT INTO city (name, province_id) VALUES ('BACOLOR', '21');
INSERT INTO city (name, province_id) VALUES ('CANDABA', '21');
INSERT INTO city (name, province_id) VALUES ('FLORIDABLANCA', '21');
INSERT INTO city (name, province_id) VALUES ('GUAGUA', '21');
INSERT INTO city (name, province_id) VALUES ('LUBAO', '21');
INSERT INTO city (name, province_id) VALUES ('MABALACAT', '21');
INSERT INTO city (name, province_id) VALUES ('MACABEBE', '21');
INSERT INTO city (name, province_id) VALUES ('MAGALANG', '21');
INSERT INTO city (name, province_id) VALUES ('MASANTOL', '21');
INSERT INTO city (name, province_id) VALUES ('MEXICO', '21');
INSERT INTO city (name, province_id) VALUES ('MINALIN', '21');
INSERT INTO city (name, province_id) VALUES ('PORAC', '21');
INSERT INTO city (name, province_id) VALUES ('SAN SIMON', '21');
INSERT INTO city (name, province_id) VALUES ('SANTA RITA', '21');
INSERT INTO city (name, province_id) VALUES ('SASMUAN (Sexmoan)', '21');
INSERT INTO city (name, province_id) VALUES ('BAMBAN', '22');
INSERT INTO city (name, province_id) VALUES ('CAMILING', '22');
INSERT INTO city (name, province_id) VALUES ('CAPAS', '22');
INSERT INTO city (name, province_id) VALUES ('CONCEPCION', '22');
INSERT INTO city (name, province_id) VALUES ('GERONA', '22');
INSERT INTO city (name, province_id) VALUES ('MAYANTOC', '22');
INSERT INTO city (name, province_id) VALUES ('MONCADA', '22');
INSERT INTO city (name, province_id) VALUES ('PANIQUI', '22');
INSERT INTO city (name, province_id) VALUES ('PURA', '22');
INSERT INTO city (name, province_id) VALUES ('RAMOS', '22');
INSERT INTO city (name, province_id) VALUES ('SAN CLEMENTE', '22');
INSERT INTO city (name, province_id) VALUES ('SANTA IGNACIA', '22');
INSERT INTO city (name, province_id) VALUES ('CITY OF TARLAC (Capital)', '22');
INSERT INTO city (name, province_id) VALUES ('VICTORIA', '22');
INSERT INTO city (name, province_id) VALUES ('SAN JOSE', '22');
INSERT INTO city (name, province_id) VALUES ('CABANGAN', '23');
INSERT INTO city (name, province_id) VALUES ('CANDELARIA', '23');
INSERT INTO city (name, province_id) VALUES ('CASTILLEJOS', '23');
INSERT INTO city (name, province_id) VALUES ('IBA (Capital)', '23');
INSERT INTO city (name, province_id) VALUES ('MASINLOC', '23');
INSERT INTO city (name, province_id) VALUES ('OLONGAPO CITY', '23');
INSERT INTO city (name, province_id) VALUES ('PALAUIG', '23');
INSERT INTO city (name, province_id) VALUES ('SAN FELIPE', '23');
INSERT INTO city (name, province_id) VALUES ('SAN MARCELINO', '23');
INSERT INTO city (name, province_id) VALUES ('SAN NARCISO', '23');
INSERT INTO city (name, province_id) VALUES ('SUBIC', '23');
INSERT INTO city (name, province_id) VALUES ('BALER (Capital)', '17');
INSERT INTO city (name, province_id) VALUES ('ABUCAY', '18');
INSERT INTO city (name, province_id) VALUES ('ANGAT', '19');
INSERT INTO city (name, province_id) VALUES ('ALIAGA', '20');
INSERT INTO city (name, province_id) VALUES ('ANGELES CITY', '21');
INSERT INTO city (name, province_id) VALUES ('ANAO', '22');
INSERT INTO city (name, province_id) VALUES ('BOTOLAN', '23');
INSERT INTO city (name, province_id) VALUES ('ALITAGTAG', '24');
INSERT INTO city (name, province_id) VALUES ('BALAYAN', '24');
INSERT INTO city (name, province_id) VALUES ('BALETE', '24');
INSERT INTO city (name, province_id) VALUES ('BATANGAS CITY (Capital)', '24');
INSERT INTO city (name, province_id) VALUES ('BAUAN', '24');
INSERT INTO city (name, province_id) VALUES ('CALACA', '24');
INSERT INTO city (name, province_id) VALUES ('CALATAGAN', '24');
INSERT INTO city (name, province_id) VALUES ('CUENCA', '24');
INSERT INTO city (name, province_id) VALUES ('IBAAN', '24');
INSERT INTO city (name, province_id) VALUES ('LAUREL', '24');
INSERT INTO city (name, province_id) VALUES ('LEMERY', '24');
INSERT INTO city (name, province_id) VALUES ('LIAN', '24');
INSERT INTO city (name, province_id) VALUES ('LIPA CITY', '24');
INSERT INTO city (name, province_id) VALUES ('LOBO', '24');
INSERT INTO city (name, province_id) VALUES ('MALVAR', '24');
INSERT INTO city (name, province_id) VALUES ('MATAASNAKAHOY', '24');
INSERT INTO city (name, province_id) VALUES ('NASUGBU', '24');
INSERT INTO city (name, province_id) VALUES ('PADRE GARCIA', '24');
INSERT INTO city (name, province_id) VALUES ('SAN PASCUAL', '24');
INSERT INTO city (name, province_id) VALUES ('TAAL', '24');
INSERT INTO city (name, province_id) VALUES ('TALISAY', '24');
INSERT INTO city (name, province_id) VALUES ('CITY OF TANAUAN', '24');
INSERT INTO city (name, province_id) VALUES ('TAYSAN', '24');
INSERT INTO city (name, province_id) VALUES ('TINGLOY', '24');
INSERT INTO city (name, province_id) VALUES ('TUY', '24');
INSERT INTO city (name, province_id) VALUES ('AMADEO', '25');
INSERT INTO city (name, province_id) VALUES ('BACOOR', '25');
INSERT INTO city (name, province_id) VALUES ('CARMONA', '25');
INSERT INTO city (name, province_id) VALUES ('CAVITE CITY', '25');
INSERT INTO city (name, province_id) VALUES ('CITY OF DASMARIÑAS', '25');
INSERT INTO city (name, province_id) VALUES ('GENERAL EMILIO AGUINALDO', '25');
INSERT INTO city (name, province_id) VALUES ('GENERAL TRIAS', '25');
INSERT INTO city (name, province_id) VALUES ('IMUS', '25');
INSERT INTO city (name, province_id) VALUES ('INDANG', '25');
INSERT INTO city (name, province_id) VALUES ('KAWIT', '25');
INSERT INTO city (name, province_id) VALUES ('MAGALLANES', '25');
INSERT INTO city (name, province_id) VALUES ('MARAGONDON', '25');
INSERT INTO city (name, province_id) VALUES ('MENDEZ (MENDEZ-NUÑEZ)', '25');
INSERT INTO city (name, province_id) VALUES ('NAIC', '25');
INSERT INTO city (name, province_id) VALUES ('NOVELETA', '25');
INSERT INTO city (name, province_id) VALUES ('SILANG', '25');
INSERT INTO city (name, province_id) VALUES ('TAGAYTAY CITY', '25');
INSERT INTO city (name, province_id) VALUES ('TANZA', '25');
INSERT INTO city (name, province_id) VALUES ('TERNATE', '25');
INSERT INTO city (name, province_id) VALUES ('TRECE MARTIRES CITY (Capital)', '25');
INSERT INTO city (name, province_id) VALUES ('GEN. MARIANO ALVAREZ', '25');
INSERT INTO city (name, province_id) VALUES ('BAY', '26');
INSERT INTO city (name, province_id) VALUES ('CITY OF BIÑAN', '26');
INSERT INTO city (name, province_id) VALUES ('CABUYAO', '26');
INSERT INTO city (name, province_id) VALUES ('CITY OF CALAMBA', '26');
INSERT INTO city (name, province_id) VALUES ('CALAUAN', '26');
INSERT INTO city (name, province_id) VALUES ('CAVINTI', '26');
INSERT INTO city (name, province_id) VALUES ('FAMY', '26');
INSERT INTO city (name, province_id) VALUES ('KALAYAAN', '26');
INSERT INTO city (name, province_id) VALUES ('LILIW', '26');
INSERT INTO city (name, province_id) VALUES ('LOS BAÑOS', '26');
INSERT INTO city (name, province_id) VALUES ('LUISIANA', '26');
INSERT INTO city (name, province_id) VALUES ('LUMBAN', '26');
INSERT INTO city (name, province_id) VALUES ('MABITAC', '26');
INSERT INTO city (name, province_id) VALUES ('MAGDALENA', '26');
INSERT INTO city (name, province_id) VALUES ('MAJAYJAY', '26');
INSERT INTO city (name, province_id) VALUES ('NAGCARLAN', '26');
INSERT INTO city (name, province_id) VALUES ('PAETE', '26');
INSERT INTO city (name, province_id) VALUES ('PAGSANJAN', '26');
INSERT INTO city (name, province_id) VALUES ('PAKIL', '26');
INSERT INTO city (name, province_id) VALUES ('PANGIL', '26');
INSERT INTO city (name, province_id) VALUES ('PILA', '26');
INSERT INTO city (name, province_id) VALUES ('SAN PABLO CITY', '26');
INSERT INTO city (name, province_id) VALUES ('SAN PEDRO', '26');
INSERT INTO city (name, province_id) VALUES ('SANTA CRUZ (Capital)', '26');
INSERT INTO city (name, province_id) VALUES ('CITY OF SANTA ROSA', '26');
INSERT INTO city (name, province_id) VALUES ('SINILOAN', '26');
INSERT INTO city (name, province_id) VALUES ('ALABAT', '27');
INSERT INTO city (name, province_id) VALUES ('ATIMONAN', '27');
INSERT INTO city (name, province_id) VALUES ('BUENAVISTA', '27');
INSERT INTO city (name, province_id) VALUES ('BURDEOS', '27');
INSERT INTO city (name, province_id) VALUES ('CALAUAG', '27');
INSERT INTO city (name, province_id) VALUES ('CATANAUAN', '27');
INSERT INTO city (name, province_id) VALUES ('GENERAL LUNA', '27');
INSERT INTO city (name, province_id) VALUES ('GENERAL NAKAR', '27');
INSERT INTO city (name, province_id) VALUES ('GUINAYANGAN', '27');
INSERT INTO city (name, province_id) VALUES ('GUMACA', '27');
INSERT INTO city (name, province_id) VALUES ('JOMALIG', '27');
INSERT INTO city (name, province_id) VALUES ('LOPEZ', '27');
INSERT INTO city (name, province_id) VALUES ('LUCBAN', '27');
INSERT INTO city (name, province_id) VALUES ('LUCENA CITY (Capital)', '27');
INSERT INTO city (name, province_id) VALUES ('MACALELON', '27');
INSERT INTO city (name, province_id) VALUES ('MAUBAN', '27');
INSERT INTO city (name, province_id) VALUES ('MULANAY', '27');
INSERT INTO city (name, province_id) VALUES ('PADRE BURGOS', '27');
INSERT INTO city (name, province_id) VALUES ('PAGBILAO', '27');
INSERT INTO city (name, province_id) VALUES ('PANUKULAN', '27');
INSERT INTO city (name, province_id) VALUES ('PATNANUNGAN', '27');
INSERT INTO city (name, province_id) VALUES ('PEREZ', '27');
INSERT INTO city (name, province_id) VALUES ('PITOGO', '27');
INSERT INTO city (name, province_id) VALUES ('POLILLO', '27');
INSERT INTO city (name, province_id) VALUES ('REAL', '27');
INSERT INTO city (name, province_id) VALUES ('SAMPALOC', '27');
INSERT INTO city (name, province_id) VALUES ('SAN ANDRES', '27');
INSERT INTO city (name, province_id) VALUES ('SAN FRANCISCO (AURORA)', '27');
INSERT INTO city (name, province_id) VALUES ('SARIAYA', '27');
INSERT INTO city (name, province_id) VALUES ('TAGKAWAYAN', '27');
INSERT INTO city (name, province_id) VALUES ('CITY OF TAYABAS', '27');
INSERT INTO city (name, province_id) VALUES ('TIAONG', '27');
INSERT INTO city (name, province_id) VALUES ('UNISAN', '27');
INSERT INTO city (name, province_id) VALUES ('CITY OF ANTIPOLO', '28');
INSERT INTO city (name, province_id) VALUES ('BARAS', '28');
INSERT INTO city (name, province_id) VALUES ('BINANGONAN', '28');
INSERT INTO city (name, province_id) VALUES ('CAINTA', '28');
INSERT INTO city (name, province_id) VALUES ('CARDONA', '28');
INSERT INTO city (name, province_id) VALUES ('JALA-JALA', '28');
INSERT INTO city (name, province_id) VALUES ('RODRIGUEZ (MONTALBAN)', '28');
INSERT INTO city (name, province_id) VALUES ('PILILLA', '28');
INSERT INTO city (name, province_id) VALUES ('TANAY', '28');
INSERT INTO city (name, province_id) VALUES ('TAYTAY', '28');
INSERT INTO city (name, province_id) VALUES ('TERESA', '28');
INSERT INTO city (name, province_id) VALUES ('AGONCILLO', '24');
INSERT INTO city (name, province_id) VALUES ('ALFONSO', '25');
INSERT INTO city (name, province_id) VALUES ('ALAMINOS', '26');
INSERT INTO city (name, province_id) VALUES ('AGDANGAN', '27');
INSERT INTO city (name, province_id) VALUES ('ANGONO', '28');
INSERT INTO city (name, province_id) VALUES ('GASAN', '29');
INSERT INTO city (name, province_id) VALUES ('MOGPOG', '29');
INSERT INTO city (name, province_id) VALUES ('TORRIJOS', '29');
INSERT INTO city (name, province_id) VALUES ('CALINTAAN', '30');
INSERT INTO city (name, province_id) VALUES ('LOOC', '30');
INSERT INTO city (name, province_id) VALUES ('LUBANG', '30');
INSERT INTO city (name, province_id) VALUES ('MAGSAYSAY', '30');
INSERT INTO city (name, province_id) VALUES ('MAMBURAO (Capital)', '30');
INSERT INTO city (name, province_id) VALUES ('PALUAN', '30');
INSERT INTO city (name, province_id) VALUES ('SABLAYAN', '30');
INSERT INTO city (name, province_id) VALUES ('BANSUD', '31');
INSERT INTO city (name, province_id) VALUES ('BONGABONG', '31');
INSERT INTO city (name, province_id) VALUES ('BULALACAO (SAN PEDRO)', '31');
INSERT INTO city (name, province_id) VALUES ('CITY OF CALAPAN (Capital)', '31');
INSERT INTO city (name, province_id) VALUES ('GLORIA', '31');
INSERT INTO city (name, province_id) VALUES ('MANSALAY', '31');
INSERT INTO city (name, province_id) VALUES ('NAUJAN', '31');
INSERT INTO city (name, province_id) VALUES ('PINAMALAYAN', '31');
INSERT INTO city (name, province_id) VALUES ('POLA', '31');
INSERT INTO city (name, province_id) VALUES ('PUERTO GALERA', '31');
INSERT INTO city (name, province_id) VALUES ('SAN TEODORO', '31');
INSERT INTO city (name, province_id) VALUES ('SOCORRO', '31');
INSERT INTO city (name, province_id) VALUES ('AGUTAYA', '32');
INSERT INTO city (name, province_id) VALUES ('ARACELI', '32');
INSERT INTO city (name, province_id) VALUES ('BALABAC', '32');
INSERT INTO city (name, province_id) VALUES ('BATARAZA', '32');
INSERT INTO city (name, province_id) VALUES ('BUSUANGA', '32');
INSERT INTO city (name, province_id) VALUES ('CAGAYANCILLO', '32');
INSERT INTO city (name, province_id) VALUES ('CORON', '32');
INSERT INTO city (name, province_id) VALUES ('CUYO', '32');
INSERT INTO city (name, province_id) VALUES ('DUMARAN', '32');
INSERT INTO city (name, province_id) VALUES ('EL NIDO (BACUIT)', '32');
INSERT INTO city (name, province_id) VALUES ('LINAPACAN', '32');
INSERT INTO city (name, province_id) VALUES ('NARRA', '32');
INSERT INTO city (name, province_id) VALUES ('PUERTO PRINCESA CITY (Capital)', '32');
INSERT INTO city (name, province_id) VALUES ('CULION', '32');
INSERT INTO city (name, province_id) VALUES ('RIZAL (MARCOS)', '32');
INSERT INTO city (name, province_id) VALUES ('SOFRONIO ESPAÑOLA', '32');
INSERT INTO city (name, province_id) VALUES ('BANTON', '33');
INSERT INTO city (name, province_id) VALUES ('CAJIDIOCAN', '33');
INSERT INTO city (name, province_id) VALUES ('CALATRAVA', '33');
INSERT INTO city (name, province_id) VALUES ('CORCUERA', '33');
INSERT INTO city (name, province_id) VALUES ('MAGDIWANG', '33');
INSERT INTO city (name, province_id) VALUES ('ODIONGAN', '33');
INSERT INTO city (name, province_id) VALUES ('ROMBLON (Capital)', '33');
INSERT INTO city (name, province_id) VALUES ('SAN FERNANDO', '33');
INSERT INTO city (name, province_id) VALUES ('FERROL', '33');
INSERT INTO city (name, province_id) VALUES ('SANTA MARIA (IMELDA)', '33');
INSERT INTO city (name, province_id) VALUES ('BOAC (Capital)', '29');
INSERT INTO city (name, province_id) VALUES ('ABRA DE ILOG', '30');
INSERT INTO city (name, province_id) VALUES ('BACO', '31');
INSERT INTO city (name, province_id) VALUES ('ABORLAN', '32');
INSERT INTO city (name, province_id) VALUES ('ALCANTARA', '33');
INSERT INTO city (name, province_id) VALUES ('CAMALIG', '34');
INSERT INTO city (name, province_id) VALUES ('DARAGA (LOCSIN)', '34');
INSERT INTO city (name, province_id) VALUES ('GUINOBATAN', '34');
INSERT INTO city (name, province_id) VALUES ('JOVELLAR', '34');
INSERT INTO city (name, province_id) VALUES ('LEGAZPI CITY (Capital)', '34');
INSERT INTO city (name, province_id) VALUES ('LIBON', '34');
INSERT INTO city (name, province_id) VALUES ('CITY OF LIGAO', '34');
INSERT INTO city (name, province_id) VALUES ('MALILIPOT', '34');
INSERT INTO city (name, province_id) VALUES ('MALINAO', '34');
INSERT INTO city (name, province_id) VALUES ('MANITO', '34');
INSERT INTO city (name, province_id) VALUES ('OAS', '34');
INSERT INTO city (name, province_id) VALUES ('PIO DURAN', '34');
INSERT INTO city (name, province_id) VALUES ('POLANGUI', '34');
INSERT INTO city (name, province_id) VALUES ('RAPU-RAPU', '34');
INSERT INTO city (name, province_id) VALUES ('SANTO DOMINGO (LIBOG)', '34');
INSERT INTO city (name, province_id) VALUES ('CITY OF TABACO', '34');
INSERT INTO city (name, province_id) VALUES ('TIWI', '34');
INSERT INTO city (name, province_id) VALUES ('CAPALONGA', '35');
INSERT INTO city (name, province_id) VALUES ('DAET (Capital)', '35');
INSERT INTO city (name, province_id) VALUES ('SAN LORENZO RUIZ (IMELDA)', '35');
INSERT INTO city (name, province_id) VALUES ('JOSE PANGANIBAN', '35');
INSERT INTO city (name, province_id) VALUES ('LABO', '35');
INSERT INTO city (name, province_id) VALUES ('MERCEDES', '35');
INSERT INTO city (name, province_id) VALUES ('PARACALE', '35');
INSERT INTO city (name, province_id) VALUES ('SANTA ELENA', '35');
INSERT INTO city (name, province_id) VALUES ('VINZONS', '35');
INSERT INTO city (name, province_id) VALUES ('BALATAN', '36');
INSERT INTO city (name, province_id) VALUES ('BATO', '36');
INSERT INTO city (name, province_id) VALUES ('BOMBON', '36');
INSERT INTO city (name, province_id) VALUES ('BUHI', '36');
INSERT INTO city (name, province_id) VALUES ('BULA', '36');
INSERT INTO city (name, province_id) VALUES ('CABUSAO', '36');
INSERT INTO city (name, province_id) VALUES ('CALABANGA', '36');
INSERT INTO city (name, province_id) VALUES ('CAMALIGAN', '36');
INSERT INTO city (name, province_id) VALUES ('CANAMAN', '36');
INSERT INTO city (name, province_id) VALUES ('CARAMOAN', '36');
INSERT INTO city (name, province_id) VALUES ('DEL GALLEGO', '36');
INSERT INTO city (name, province_id) VALUES ('GAINZA', '36');
INSERT INTO city (name, province_id) VALUES ('GARCHITORENA', '36');
INSERT INTO city (name, province_id) VALUES ('GOA', '36');
INSERT INTO city (name, province_id) VALUES ('IRIGA CITY', '36');
INSERT INTO city (name, province_id) VALUES ('LAGONOY', '36');
INSERT INTO city (name, province_id) VALUES ('LIBMANAN', '36');
INSERT INTO city (name, province_id) VALUES ('LUPI', '36');
INSERT INTO city (name, province_id) VALUES ('MAGARAO', '36');
INSERT INTO city (name, province_id) VALUES ('MILAOR', '36');
INSERT INTO city (name, province_id) VALUES ('MINALABAC', '36');
INSERT INTO city (name, province_id) VALUES ('NABUA', '36');
INSERT INTO city (name, province_id) VALUES ('NAGA CITY', '36');
INSERT INTO city (name, province_id) VALUES ('OCAMPO', '36');
INSERT INTO city (name, province_id) VALUES ('PASACAO', '36');
INSERT INTO city (name, province_id) VALUES ('PILI (Capital)', '36');
INSERT INTO city (name, province_id) VALUES ('PRESENTACION (PARUBCAN)', '36');
INSERT INTO city (name, province_id) VALUES ('RAGAY', '36');
INSERT INTO city (name, province_id) VALUES ('SAGÑAY', '36');
INSERT INTO city (name, province_id) VALUES ('SIPOCOT', '36');
INSERT INTO city (name, province_id) VALUES ('SIRUMA', '36');
INSERT INTO city (name, province_id) VALUES ('TIGAON', '36');
INSERT INTO city (name, province_id) VALUES ('TINAMBAC', '36');
INSERT INTO city (name, province_id) VALUES ('CARAMORAN', '37');
INSERT INTO city (name, province_id) VALUES ('GIGMOTO', '37');
INSERT INTO city (name, province_id) VALUES ('PANDAN', '37');
INSERT INTO city (name, province_id) VALUES ('PANGANIBAN (PAYO)', '37');
INSERT INTO city (name, province_id) VALUES ('SAN ANDRES (CALOLBON)', '37');
INSERT INTO city (name, province_id) VALUES ('VIGA', '37');
INSERT INTO city (name, province_id) VALUES ('VIRAC (Capital)', '37');
INSERT INTO city (name, province_id) VALUES ('BALENO', '38');
INSERT INTO city (name, province_id) VALUES ('BALUD', '38');
INSERT INTO city (name, province_id) VALUES ('BATUAN', '38');
INSERT INTO city (name, province_id) VALUES ('CATAINGAN', '38');
INSERT INTO city (name, province_id) VALUES ('CAWAYAN', '38');
INSERT INTO city (name, province_id) VALUES ('DIMASALANG', '38');
INSERT INTO city (name, province_id) VALUES ('ESPERANZA', '38');
INSERT INTO city (name, province_id) VALUES ('MANDAON', '38');
INSERT INTO city (name, province_id) VALUES ('CITY OF MASBATE (Capital)', '38');
INSERT INTO city (name, province_id) VALUES ('MILAGROS', '38');
INSERT INTO city (name, province_id) VALUES ('MOBO', '38');
INSERT INTO city (name, province_id) VALUES ('MONREAL', '38');
INSERT INTO city (name, province_id) VALUES ('PALANAS', '38');
INSERT INTO city (name, province_id) VALUES ('PIO V. CORPUZ (LIMBUHAN)', '38');
INSERT INTO city (name, province_id) VALUES ('PLACER', '38');
INSERT INTO city (name, province_id) VALUES ('USON', '38');
INSERT INTO city (name, province_id) VALUES ('BULAN', '39');
INSERT INTO city (name, province_id) VALUES ('BULUSAN', '39');
INSERT INTO city (name, province_id) VALUES ('CASTILLA', '39');
INSERT INTO city (name, province_id) VALUES ('DONSOL', '39');
INSERT INTO city (name, province_id) VALUES ('GUBAT', '39');
INSERT INTO city (name, province_id) VALUES ('IROSIN', '39');
INSERT INTO city (name, province_id) VALUES ('JUBAN', '39');
INSERT INTO city (name, province_id) VALUES ('MATNOG', '39');
INSERT INTO city (name, province_id) VALUES ('PRIETO DIAZ', '39');
INSERT INTO city (name, province_id) VALUES ('SANTA MAGDALENA', '39');
INSERT INTO city (name, province_id) VALUES ('CITY OF SORSOGON (Capital)', '39');
INSERT INTO city (name, province_id) VALUES ('BACACAY', '34');
INSERT INTO city (name, province_id) VALUES ('BASUD', '35');
INSERT INTO city (name, province_id) VALUES ('BAAO', '36');
INSERT INTO city (name, province_id) VALUES ('BAGAMANOC', '37');
INSERT INTO city (name, province_id) VALUES ('AROROY', '38');
INSERT INTO city (name, province_id) VALUES ('BARCELONA', '39');
INSERT INTO city (name, province_id) VALUES ('BANGA', '40');
INSERT INTO city (name, province_id) VALUES ('BATAN', '40');
INSERT INTO city (name, province_id) VALUES ('BURUANGA', '40');
INSERT INTO city (name, province_id) VALUES ('IBAJAY', '40');
INSERT INTO city (name, province_id) VALUES ('KALIBO (Capital)', '40');
INSERT INTO city (name, province_id) VALUES ('LEZO', '40');
INSERT INTO city (name, province_id) VALUES ('LIBACAO', '40');
INSERT INTO city (name, province_id) VALUES ('MADALAG', '40');
INSERT INTO city (name, province_id) VALUES ('MAKATO', '40');
INSERT INTO city (name, province_id) VALUES ('MALAY', '40');
INSERT INTO city (name, province_id) VALUES ('NABAS', '40');
INSERT INTO city (name, province_id) VALUES ('NEW WASHINGTON', '40');
INSERT INTO city (name, province_id) VALUES ('NUMANCIA', '40');
INSERT INTO city (name, province_id) VALUES ('TANGALAN', '40');
INSERT INTO city (name, province_id) VALUES ('BARBAZA', '41');
INSERT INTO city (name, province_id) VALUES ('BELISON', '41');
INSERT INTO city (name, province_id) VALUES ('BUGASONG', '41');
INSERT INTO city (name, province_id) VALUES ('CALUYA', '41');
INSERT INTO city (name, province_id) VALUES ('CULASI', '41');
INSERT INTO city (name, province_id) VALUES ('TOBIAS FORNIER (DAO)', '41');
INSERT INTO city (name, province_id) VALUES ('HAMTIC', '41');
INSERT INTO city (name, province_id) VALUES ('LAUA-AN', '41');
INSERT INTO city (name, province_id) VALUES ('LIBERTAD', '41');
INSERT INTO city (name, province_id) VALUES ('PATNONGON', '41');
INSERT INTO city (name, province_id) VALUES ('SAN JOSE (Capital)', '41');
INSERT INTO city (name, province_id) VALUES ('SAN REMIGIO', '41');
INSERT INTO city (name, province_id) VALUES ('SEBASTE', '41');
INSERT INTO city (name, province_id) VALUES ('SIBALOM', '41');
INSERT INTO city (name, province_id) VALUES ('TIBIAO', '41');
INSERT INTO city (name, province_id) VALUES ('VALDERRAMA', '41');
INSERT INTO city (name, province_id) VALUES ('DAO', '42');
INSERT INTO city (name, province_id) VALUES ('DUMALAG', '42');
INSERT INTO city (name, province_id) VALUES ('DUMARAO', '42');
INSERT INTO city (name, province_id) VALUES ('IVISAN', '42');
INSERT INTO city (name, province_id) VALUES ('JAMINDAN', '42');
INSERT INTO city (name, province_id) VALUES ('MA-AYON', '42');
INSERT INTO city (name, province_id) VALUES ('MAMBUSAO', '42');
INSERT INTO city (name, province_id) VALUES ('PANAY', '42');
INSERT INTO city (name, province_id) VALUES ('PANITAN', '42');
INSERT INTO city (name, province_id) VALUES ('PONTEVEDRA', '42');
INSERT INTO city (name, province_id) VALUES ('PRESIDENT ROXAS', '42');
INSERT INTO city (name, province_id) VALUES ('ROXAS CITY (Capital)', '42');
INSERT INTO city (name, province_id) VALUES ('SAPI-AN', '42');
INSERT INTO city (name, province_id) VALUES ('SIGMA', '42');
INSERT INTO city (name, province_id) VALUES ('TAPAZ', '42');
INSERT INTO city (name, province_id) VALUES ('JORDAN (Capital)', '43');
INSERT INTO city (name, province_id) VALUES ('NUEVA VALENCIA', '43');
INSERT INTO city (name, province_id) VALUES ('SAN LORENZO', '43');
INSERT INTO city (name, province_id) VALUES ('SIBUNAG', '43');
INSERT INTO city (name, province_id) VALUES ('ALIMODIAN', '44');
INSERT INTO city (name, province_id) VALUES ('ANILAO', '44');
INSERT INTO city (name, province_id) VALUES ('BADIANGAN', '44');
INSERT INTO city (name, province_id) VALUES ('BALASAN', '44');
INSERT INTO city (name, province_id) VALUES ('BANATE', '44');
INSERT INTO city (name, province_id) VALUES ('BAROTAC NUEVO', '44');
INSERT INTO city (name, province_id) VALUES ('BAROTAC VIEJO', '44');
INSERT INTO city (name, province_id) VALUES ('BATAD', '44');
INSERT INTO city (name, province_id) VALUES ('BINGAWAN', '44');
INSERT INTO city (name, province_id) VALUES ('CALINOG', '44');
INSERT INTO city (name, province_id) VALUES ('CARLES', '44');
INSERT INTO city (name, province_id) VALUES ('DINGLE', '44');
INSERT INTO city (name, province_id) VALUES ('DUEÑAS', '44');
INSERT INTO city (name, province_id) VALUES ('DUMANGAS', '44');
INSERT INTO city (name, province_id) VALUES ('ESTANCIA', '44');
INSERT INTO city (name, province_id) VALUES ('GUIMBAL', '44');
INSERT INTO city (name, province_id) VALUES ('IGBARAS', '44');
INSERT INTO city (name, province_id) VALUES ('ILOILO CITY (Capital)', '44');
INSERT INTO city (name, province_id) VALUES ('JANIUAY', '44');
INSERT INTO city (name, province_id) VALUES ('LAMBUNAO', '44');
INSERT INTO city (name, province_id) VALUES ('LEGANES', '44');
INSERT INTO city (name, province_id) VALUES ('LEON', '44');
INSERT INTO city (name, province_id) VALUES ('MAASIN', '44');
INSERT INTO city (name, province_id) VALUES ('MIAGAO', '44');
INSERT INTO city (name, province_id) VALUES ('MINA', '44');
INSERT INTO city (name, province_id) VALUES ('NEW LUCENA', '44');
INSERT INTO city (name, province_id) VALUES ('OTON', '44');
INSERT INTO city (name, province_id) VALUES ('CITY OF PASSI', '44');
INSERT INTO city (name, province_id) VALUES ('PAVIA', '44');
INSERT INTO city (name, province_id) VALUES ('POTOTAN', '44');
INSERT INTO city (name, province_id) VALUES ('SAN DIONISIO', '44');
INSERT INTO city (name, province_id) VALUES ('SAN ENRIQUE', '44');
INSERT INTO city (name, province_id) VALUES ('SAN JOAQUIN', '44');
INSERT INTO city (name, province_id) VALUES ('SARA', '44');
INSERT INTO city (name, province_id) VALUES ('TIGBAUAN', '44');
INSERT INTO city (name, province_id) VALUES ('TUBUNGAN', '44');
INSERT INTO city (name, province_id) VALUES ('ZARRAGA', '44');
INSERT INTO city (name, province_id) VALUES ('BAGO CITY', '45');
INSERT INTO city (name, province_id) VALUES ('BINALBAGAN', '45');
INSERT INTO city (name, province_id) VALUES ('CADIZ CITY', '45');
INSERT INTO city (name, province_id) VALUES ('CANDONI', '45');
INSERT INTO city (name, province_id) VALUES ('CAUAYAN', '45');
INSERT INTO city (name, province_id) VALUES ('ENRIQUE B. MAGALONA (SARAVIA)', '45');
INSERT INTO city (name, province_id) VALUES ('CITY OF ESCALANTE', '45');
INSERT INTO city (name, province_id) VALUES ('CITY OF HIMAMAYLAN', '45');
INSERT INTO city (name, province_id) VALUES ('HINIGARAN', '45');
INSERT INTO city (name, province_id) VALUES ('HINOBA-AN (ASIA)', '45');
INSERT INTO city (name, province_id) VALUES ('ILOG', '45');
INSERT INTO city (name, province_id) VALUES ('ISABELA', '45');
INSERT INTO city (name, province_id) VALUES ('CITY OF KABANKALAN', '45');
INSERT INTO city (name, province_id) VALUES ('LA CARLOTA CITY', '45');
INSERT INTO city (name, province_id) VALUES ('LA CASTELLANA', '45');
INSERT INTO city (name, province_id) VALUES ('MANAPLA', '45');
INSERT INTO city (name, province_id) VALUES ('MOISES PADILLA (MAGALLON)', '45');
INSERT INTO city (name, province_id) VALUES ('MURCIA', '45');
INSERT INTO city (name, province_id) VALUES ('PULUPANDAN', '45');
INSERT INTO city (name, province_id) VALUES ('SAGAY CITY', '45');
INSERT INTO city (name, province_id) VALUES ('SILAY CITY', '45');
INSERT INTO city (name, province_id) VALUES ('CITY OF SIPALAY', '45');
INSERT INTO city (name, province_id) VALUES ('CITY OF TALISAY', '45');
INSERT INTO city (name, province_id) VALUES ('TOBOSO', '45');
INSERT INTO city (name, province_id) VALUES ('VALLADOLID', '45');
INSERT INTO city (name, province_id) VALUES ('CITY OF VICTORIAS', '45');
INSERT INTO city (name, province_id) VALUES ('SALVADOR BENEDICTO', '45');
INSERT INTO city (name, province_id) VALUES ('ALTAVAS', '40');
INSERT INTO city (name, province_id) VALUES ('ANINI-Y', '41');
INSERT INTO city (name, province_id) VALUES ('CUARTERO', '42');
INSERT INTO city (name, province_id) VALUES ('AJUY', '44');
INSERT INTO city (name, province_id) VALUES ('BACOLOD CITY (Capital)', '45');
INSERT INTO city (name, province_id) VALUES ('ANTEQUERA', '46');
INSERT INTO city (name, province_id) VALUES ('BACLAYON', '46');
INSERT INTO city (name, province_id) VALUES ('BALILIHAN', '46');
INSERT INTO city (name, province_id) VALUES ('BILAR', '46');
INSERT INTO city (name, province_id) VALUES ('CALAPE', '46');
INSERT INTO city (name, province_id) VALUES ('CANDIJAY', '46');
INSERT INTO city (name, province_id) VALUES ('CARMEN', '46');
INSERT INTO city (name, province_id) VALUES ('CATIGBIAN', '46');
INSERT INTO city (name, province_id) VALUES ('CLARIN', '46');
INSERT INTO city (name, province_id) VALUES ('CORELLA', '46');
INSERT INTO city (name, province_id) VALUES ('CORTES', '46');
INSERT INTO city (name, province_id) VALUES ('DAGOHOY', '46');
INSERT INTO city (name, province_id) VALUES ('DANAO', '46');
INSERT INTO city (name, province_id) VALUES ('DAUIS', '46');
INSERT INTO city (name, province_id) VALUES ('DIMIAO', '46');
INSERT INTO city (name, province_id) VALUES ('DUERO', '46');
INSERT INTO city (name, province_id) VALUES ('GARCIA HERNANDEZ', '46');
INSERT INTO city (name, province_id) VALUES ('GUINDULMAN', '46');
INSERT INTO city (name, province_id) VALUES ('INABANGA', '46');
INSERT INTO city (name, province_id) VALUES ('JAGNA', '46');
INSERT INTO city (name, province_id) VALUES ('GETAFE', '46');
INSERT INTO city (name, province_id) VALUES ('LILA', '46');
INSERT INTO city (name, province_id) VALUES ('LOAY', '46');
INSERT INTO city (name, province_id) VALUES ('LOBOC', '46');
INSERT INTO city (name, province_id) VALUES ('LOON', '46');
INSERT INTO city (name, province_id) VALUES ('MARIBOJOC', '46');
INSERT INTO city (name, province_id) VALUES ('PANGLAO', '46');
INSERT INTO city (name, province_id) VALUES ('PRES. CARLOS P. GARCIA (PITOGO)', '46');
INSERT INTO city (name, province_id) VALUES ('SAGBAYAN (BORJA)', '46');
INSERT INTO city (name, province_id) VALUES ('SEVILLA', '46');
INSERT INTO city (name, province_id) VALUES ('SIERRA BULLONES', '46');
INSERT INTO city (name, province_id) VALUES ('SIKATUNA', '46');
INSERT INTO city (name, province_id) VALUES ('TAGBILARAN CITY (Capital)', '46');
INSERT INTO city (name, province_id) VALUES ('TALIBON', '46');
INSERT INTO city (name, province_id) VALUES ('TRINIDAD', '46');
INSERT INTO city (name, province_id) VALUES ('TUBIGON', '46');
INSERT INTO city (name, province_id) VALUES ('UBAY', '46');
INSERT INTO city (name, province_id) VALUES ('VALENCIA', '46');
INSERT INTO city (name, province_id) VALUES ('BIEN UNIDO', '46');
INSERT INTO city (name, province_id) VALUES ('ALCOY', '47');
INSERT INTO city (name, province_id) VALUES ('ALEGRIA', '47');
INSERT INTO city (name, province_id) VALUES ('ALOGUINSAN', '47');
INSERT INTO city (name, province_id) VALUES ('ARGAO', '47');
INSERT INTO city (name, province_id) VALUES ('ASTURIAS', '47');
INSERT INTO city (name, province_id) VALUES ('BADIAN', '47');
INSERT INTO city (name, province_id) VALUES ('BALAMBAN', '47');
INSERT INTO city (name, province_id) VALUES ('BANTAYAN', '47');
INSERT INTO city (name, province_id) VALUES ('BARILI', '47');
INSERT INTO city (name, province_id) VALUES ('CITY OF BOGO', '47');
INSERT INTO city (name, province_id) VALUES ('BOLJOON', '47');
INSERT INTO city (name, province_id) VALUES ('BORBON', '47');
INSERT INTO city (name, province_id) VALUES ('CITY OF CARCAR', '47');
INSERT INTO city (name, province_id) VALUES ('CATMON', '47');
INSERT INTO city (name, province_id) VALUES ('CEBU CITY (Capital)', '47');
INSERT INTO city (name, province_id) VALUES ('COMPOSTELA', '47');
INSERT INTO city (name, province_id) VALUES ('CONSOLACION', '47');
INSERT INTO city (name, province_id) VALUES ('CORDOBA', '47');
INSERT INTO city (name, province_id) VALUES ('DAANBANTAYAN', '47');
INSERT INTO city (name, province_id) VALUES ('DALAGUETE', '47');
INSERT INTO city (name, province_id) VALUES ('DANAO CITY', '47');
INSERT INTO city (name, province_id) VALUES ('DUMANJUG', '47');
INSERT INTO city (name, province_id) VALUES ('GINATILAN', '47');
INSERT INTO city (name, province_id) VALUES ('LAPU-LAPU CITY (OPON)', '47');
INSERT INTO city (name, province_id) VALUES ('LILOAN', '47');
INSERT INTO city (name, province_id) VALUES ('MADRIDEJOS', '47');
INSERT INTO city (name, province_id) VALUES ('MALABUYOC', '47');
INSERT INTO city (name, province_id) VALUES ('MANDAUE CITY', '47');
INSERT INTO city (name, province_id) VALUES ('MEDELLIN', '47');
INSERT INTO city (name, province_id) VALUES ('MINGLANILLA', '47');
INSERT INTO city (name, province_id) VALUES ('MOALBOAL', '47');
INSERT INTO city (name, province_id) VALUES ('CITY OF NAGA', '47');
INSERT INTO city (name, province_id) VALUES ('OSLOB', '47');
INSERT INTO city (name, province_id) VALUES ('PINAMUNGAHAN', '47');
INSERT INTO city (name, province_id) VALUES ('PORO', '47');
INSERT INTO city (name, province_id) VALUES ('RONDA', '47');
INSERT INTO city (name, province_id) VALUES ('SAMBOAN', '47');
INSERT INTO city (name, province_id) VALUES ('SAN FRANCISCO', '47');
INSERT INTO city (name, province_id) VALUES ('SANTANDER', '47');
INSERT INTO city (name, province_id) VALUES ('SIBONGA', '47');
INSERT INTO city (name, province_id) VALUES ('SOGOD', '47');
INSERT INTO city (name, province_id) VALUES ('TABOGON', '47');
INSERT INTO city (name, province_id) VALUES ('TABUELAN', '47');
INSERT INTO city (name, province_id) VALUES ('TOLEDO CITY', '47');
INSERT INTO city (name, province_id) VALUES ('TUBURAN', '47');
INSERT INTO city (name, province_id) VALUES ('TUDELA', '47');
INSERT INTO city (name, province_id) VALUES ('AYUNGON', '48');
INSERT INTO city (name, province_id) VALUES ('BACONG', '48');
INSERT INTO city (name, province_id) VALUES ('BAIS CITY', '48');
INSERT INTO city (name, province_id) VALUES ('BASAY', '48');
INSERT INTO city (name, province_id) VALUES ('CITY OF BAYAWAN (TULONG)', '48');
INSERT INTO city (name, province_id) VALUES ('BINDOY (PAYABON)', '48');
INSERT INTO city (name, province_id) VALUES ('CANLAON CITY', '48');
INSERT INTO city (name, province_id) VALUES ('DAUIN', '48');
INSERT INTO city (name, province_id) VALUES ('DUMAGUETE CITY (Capital)', '48');
INSERT INTO city (name, province_id) VALUES ('CITY OF GUIHULNGAN', '48');
INSERT INTO city (name, province_id) VALUES ('JIMALALUD', '48');
INSERT INTO city (name, province_id) VALUES ('LA LIBERTAD', '48');
INSERT INTO city (name, province_id) VALUES ('MABINAY', '48');
INSERT INTO city (name, province_id) VALUES ('MANJUYOD', '48');
INSERT INTO city (name, province_id) VALUES ('SIATON', '48');
INSERT INTO city (name, province_id) VALUES ('SIBULAN', '48');
INSERT INTO city (name, province_id) VALUES ('CITY OF TANJAY', '48');
INSERT INTO city (name, province_id) VALUES ('TAYASAN', '48');
INSERT INTO city (name, province_id) VALUES ('VALENCIA (LUZURRIAGA)', '48');
INSERT INTO city (name, province_id) VALUES ('VALLEHERMOSO', '48');
INSERT INTO city (name, province_id) VALUES ('ZAMBOANGUITA', '48');
INSERT INTO city (name, province_id) VALUES ('LARENA', '49');
INSERT INTO city (name, province_id) VALUES ('LAZI', '49');
INSERT INTO city (name, province_id) VALUES ('MARIA', '49');
INSERT INTO city (name, province_id) VALUES ('SIQUIJOR (Capital)', '49');
INSERT INTO city (name, province_id) VALUES ('ALBURQUERQUE', '46');
INSERT INTO city (name, province_id) VALUES ('AMLAN (AYUQUITAN)', '48');
INSERT INTO city (name, province_id) VALUES ('ENRIQUE VILLANUEVA', '49');
INSERT INTO city (name, province_id) VALUES ('BILIRAN', '50');
INSERT INTO city (name, province_id) VALUES ('CABUCGAYAN', '50');
INSERT INTO city (name, province_id) VALUES ('CAIBIRAN', '50');
INSERT INTO city (name, province_id) VALUES ('CULABA', '50');
INSERT INTO city (name, province_id) VALUES ('KAWAYAN', '50');
INSERT INTO city (name, province_id) VALUES ('MARIPIPI', '50');
INSERT INTO city (name, province_id) VALUES ('NAVAL (Capital)', '50');
INSERT INTO city (name, province_id) VALUES ('BALANGIGA', '51');
INSERT INTO city (name, province_id) VALUES ('BALANGKAYAN', '51');
INSERT INTO city (name, province_id) VALUES ('CITY OF BORONGAN (Capital)', '51');
INSERT INTO city (name, province_id) VALUES ('CAN-AVID', '51');
INSERT INTO city (name, province_id) VALUES ('GENERAL MACARTHUR', '51');
INSERT INTO city (name, province_id) VALUES ('GIPORLOS', '51');
INSERT INTO city (name, province_id) VALUES ('GUIUAN', '51');
INSERT INTO city (name, province_id) VALUES ('HERNANI', '51');
INSERT INTO city (name, province_id) VALUES ('JIPAPAD', '51');
INSERT INTO city (name, province_id) VALUES ('LAWAAN', '51');
INSERT INTO city (name, province_id) VALUES ('LLORENTE', '51');
INSERT INTO city (name, province_id) VALUES ('MASLOG', '51');
INSERT INTO city (name, province_id) VALUES ('MAYDOLONG', '51');
INSERT INTO city (name, province_id) VALUES ('ORAS', '51');
INSERT INTO city (name, province_id) VALUES ('QUINAPONDAN', '51');
INSERT INTO city (name, province_id) VALUES ('SALCEDO', '51');
INSERT INTO city (name, province_id) VALUES ('SAN JULIAN', '51');
INSERT INTO city (name, province_id) VALUES ('SAN POLICARPO', '51');
INSERT INTO city (name, province_id) VALUES ('SULAT', '51');
INSERT INTO city (name, province_id) VALUES ('TAFT', '51');
INSERT INTO city (name, province_id) VALUES ('ALANGALANG', '52');
INSERT INTO city (name, province_id) VALUES ('ALBUERA', '52');
INSERT INTO city (name, province_id) VALUES ('BABATNGON', '52');
INSERT INTO city (name, province_id) VALUES ('BARUGO', '52');
INSERT INTO city (name, province_id) VALUES ('CITY OF BAYBAY', '52');
INSERT INTO city (name, province_id) VALUES ('BURAUEN', '52');
INSERT INTO city (name, province_id) VALUES ('CALUBIAN', '52');
INSERT INTO city (name, province_id) VALUES ('CAPOOCAN', '52');
INSERT INTO city (name, province_id) VALUES ('CARIGARA', '52');
INSERT INTO city (name, province_id) VALUES ('DAGAMI', '52');
INSERT INTO city (name, province_id) VALUES ('DULAG', '52');
INSERT INTO city (name, province_id) VALUES ('HILONGOS', '52');
INSERT INTO city (name, province_id) VALUES ('HINDANG', '52');
INSERT INTO city (name, province_id) VALUES ('INOPACAN', '52');
INSERT INTO city (name, province_id) VALUES ('ISABEL', '52');
INSERT INTO city (name, province_id) VALUES ('JARO', '52');
INSERT INTO city (name, province_id) VALUES ('JAVIER (BUGHO)', '52');
INSERT INTO city (name, province_id) VALUES ('JULITA', '52');
INSERT INTO city (name, province_id) VALUES ('KANANGA', '52');
INSERT INTO city (name, province_id) VALUES ('LEYTE', '52');
INSERT INTO city (name, province_id) VALUES ('MACARTHUR', '52');
INSERT INTO city (name, province_id) VALUES ('MAHAPLAG', '52');
INSERT INTO city (name, province_id) VALUES ('MATAG-OB', '52');
INSERT INTO city (name, province_id) VALUES ('MATALOM', '52');
INSERT INTO city (name, province_id) VALUES ('MAYORGA', '52');
INSERT INTO city (name, province_id) VALUES ('MERIDA', '52');
INSERT INTO city (name, province_id) VALUES ('ORMOC CITY', '52');
INSERT INTO city (name, province_id) VALUES ('PALO', '52');
INSERT INTO city (name, province_id) VALUES ('PALOMPON', '52');
INSERT INTO city (name, province_id) VALUES ('PASTRANA', '52');
INSERT INTO city (name, province_id) VALUES ('TABANGO', '52');
INSERT INTO city (name, province_id) VALUES ('TABONTABON', '52');
INSERT INTO city (name, province_id) VALUES ('TACLOBAN CITY (Capital)', '52');
INSERT INTO city (name, province_id) VALUES ('TANAUAN', '52');
INSERT INTO city (name, province_id) VALUES ('TOLOSA', '52');
INSERT INTO city (name, province_id) VALUES ('TUNGA', '52');
INSERT INTO city (name, province_id) VALUES ('VILLABA', '52');
INSERT INTO city (name, province_id) VALUES ('BIRI', '53');
INSERT INTO city (name, province_id) VALUES ('BOBON', '53');
INSERT INTO city (name, province_id) VALUES ('CAPUL', '53');
INSERT INTO city (name, province_id) VALUES ('CATARMAN (Capital)', '53');
INSERT INTO city (name, province_id) VALUES ('CATUBIG', '53');
INSERT INTO city (name, province_id) VALUES ('GAMAY', '53');
INSERT INTO city (name, province_id) VALUES ('LAOANG', '53');
INSERT INTO city (name, province_id) VALUES ('LAPINIG', '53');
INSERT INTO city (name, province_id) VALUES ('LAS NAVAS', '53');
INSERT INTO city (name, province_id) VALUES ('LAVEZARES', '53');
INSERT INTO city (name, province_id) VALUES ('MAPANAS', '53');
INSERT INTO city (name, province_id) VALUES ('MONDRAGON', '53');
INSERT INTO city (name, province_id) VALUES ('PALAPAG', '53');
INSERT INTO city (name, province_id) VALUES ('PAMBUJAN', '53');
INSERT INTO city (name, province_id) VALUES ('SAN ROQUE', '53');
INSERT INTO city (name, province_id) VALUES ('SILVINO LOBOS', '53');
INSERT INTO city (name, province_id) VALUES ('LOPE DE VEGA', '53');
INSERT INTO city (name, province_id) VALUES ('BASEY', '54');
INSERT INTO city (name, province_id) VALUES ('CALBAYOG CITY', '54');
INSERT INTO city (name, province_id) VALUES ('CALBIGA', '54');
INSERT INTO city (name, province_id) VALUES ('CITY OF CATBALOGAN (Capital)', '54');
INSERT INTO city (name, province_id) VALUES ('DARAM', '54');
INSERT INTO city (name, province_id) VALUES ('GANDARA', '54');
INSERT INTO city (name, province_id) VALUES ('HINABANGAN', '54');
INSERT INTO city (name, province_id) VALUES ('JIABONG', '54');
INSERT INTO city (name, province_id) VALUES ('MARABUT', '54');
INSERT INTO city (name, province_id) VALUES ('MATUGUINAO', '54');
INSERT INTO city (name, province_id) VALUES ('MOTIONG', '54');
INSERT INTO city (name, province_id) VALUES ('PINABACDAO', '54');
INSERT INTO city (name, province_id) VALUES ('SAN JOSE DE BUAN', '54');
INSERT INTO city (name, province_id) VALUES ('SAN SEBASTIAN', '54');
INSERT INTO city (name, province_id) VALUES ('SANTA MARGARITA', '54');
INSERT INTO city (name, province_id) VALUES ('SANTO NIÑO', '54');
INSERT INTO city (name, province_id) VALUES ('TALALORA', '54');
INSERT INTO city (name, province_id) VALUES ('TARANGNAN', '54');
INSERT INTO city (name, province_id) VALUES ('VILLAREAL', '54');
INSERT INTO city (name, province_id) VALUES ('PARANAS (WRIGHT)', '54');
INSERT INTO city (name, province_id) VALUES ('ZUMARRAGA', '54');
INSERT INTO city (name, province_id) VALUES ('TAGAPUL-AN', '54');
INSERT INTO city (name, province_id) VALUES ('SAN JORGE', '54');
INSERT INTO city (name, province_id) VALUES ('PAGSANGHAN', '54');
INSERT INTO city (name, province_id) VALUES ('BONTOC', '55');
INSERT INTO city (name, province_id) VALUES ('HINUNANGAN', '55');
INSERT INTO city (name, province_id) VALUES ('HINUNDAYAN', '55');
INSERT INTO city (name, province_id) VALUES ('LIBAGON', '55');
INSERT INTO city (name, province_id) VALUES ('CITY OF MAASIN (Capital)', '55');
INSERT INTO city (name, province_id) VALUES ('MACROHON', '55');
INSERT INTO city (name, province_id) VALUES ('MALITBOG', '55');
INSERT INTO city (name, province_id) VALUES ('PINTUYAN', '55');
INSERT INTO city (name, province_id) VALUES ('SAINT BERNARD', '55');
INSERT INTO city (name, province_id) VALUES ('SAN JUAN (CABALIAN)', '55');
INSERT INTO city (name, province_id) VALUES ('SAN RICARDO', '55');
INSERT INTO city (name, province_id) VALUES ('SILAGO', '55');
INSERT INTO city (name, province_id) VALUES ('TOMAS OPPUS', '55');
INSERT INTO city (name, province_id) VALUES ('LIMASAWA', '55');
INSERT INTO city (name, province_id) VALUES ('ALMERIA', '50');
INSERT INTO city (name, province_id) VALUES ('ARTECHE', '51');
INSERT INTO city (name, province_id) VALUES ('ABUYOG', '52');
INSERT INTO city (name, province_id) VALUES ('ALLEN', '53');
INSERT INTO city (name, province_id) VALUES ('ALMAGRO', '54');
INSERT INTO city (name, province_id) VALUES ('ANAHAWAN', '55');
INSERT INTO city (name, province_id) VALUES ('DIPOLOG CITY (Capital)', '56');
INSERT INTO city (name, province_id) VALUES ('KATIPUNAN', '56');
INSERT INTO city (name, province_id) VALUES ('LABASON', '56');
INSERT INTO city (name, province_id) VALUES ('LILOY', '56');
INSERT INTO city (name, province_id) VALUES ('MANUKAN', '56');
INSERT INTO city (name, province_id) VALUES ('MUTIA', '56');
INSERT INTO city (name, province_id) VALUES ('PIÑAN (NEW PIÑAN)', '56');
INSERT INTO city (name, province_id) VALUES ('POLANCO', '56');
INSERT INTO city (name, province_id) VALUES ('PRES. MANUEL A. ROXAS', '56');
INSERT INTO city (name, province_id) VALUES ('SALUG', '56');
INSERT INTO city (name, province_id) VALUES ('SERGIO OSMEÑA SR.', '56');
INSERT INTO city (name, province_id) VALUES ('SIAYAN', '56');
INSERT INTO city (name, province_id) VALUES ('SIBUCO', '56');
INSERT INTO city (name, province_id) VALUES ('SIBUTAD', '56');
INSERT INTO city (name, province_id) VALUES ('SINDANGAN', '56');
INSERT INTO city (name, province_id) VALUES ('SIOCON', '56');
INSERT INTO city (name, province_id) VALUES ('SIRAWAI', '56');
INSERT INTO city (name, province_id) VALUES ('TAMPILISAN', '56');
INSERT INTO city (name, province_id) VALUES ('JOSE DALMAN (PONOT)', '56');
INSERT INTO city (name, province_id) VALUES ('GUTALAC', '56');
INSERT INTO city (name, province_id) VALUES ('BALIGUIAN', '56');
INSERT INTO city (name, province_id) VALUES ('GODOD', '56');
INSERT INTO city (name, province_id) VALUES ('BACUNGAN (Leon T. Postigo)', '56');
INSERT INTO city (name, province_id) VALUES ('KALAWIT', '56');
INSERT INTO city (name, province_id) VALUES ('BAYOG', '57');
INSERT INTO city (name, province_id) VALUES ('DIMATALING', '57');
INSERT INTO city (name, province_id) VALUES ('DINAS', '57');
INSERT INTO city (name, province_id) VALUES ('DUMALINAO', '57');
INSERT INTO city (name, province_id) VALUES ('DUMINGAG', '57');
INSERT INTO city (name, province_id) VALUES ('KUMALARANG', '57');
INSERT INTO city (name, province_id) VALUES ('LABANGAN', '57');
INSERT INTO city (name, province_id) VALUES ('LAPUYAN', '57');
INSERT INTO city (name, province_id) VALUES ('MAHAYAG', '57');
INSERT INTO city (name, province_id) VALUES ('MARGOSATUBIG', '57');
INSERT INTO city (name, province_id) VALUES ('MIDSALIP', '57');
INSERT INTO city (name, province_id) VALUES ('MOLAVE', '57');
INSERT INTO city (name, province_id) VALUES ('PAGADIAN CITY (Capital)', '57');
INSERT INTO city (name, province_id) VALUES ('RAMON MAGSAYSAY (LIARGO)', '57');
INSERT INTO city (name, province_id) VALUES ('TABINA', '57');
INSERT INTO city (name, province_id) VALUES ('TAMBULIG', '57');
INSERT INTO city (name, province_id) VALUES ('TUKURAN', '57');
INSERT INTO city (name, province_id) VALUES ('ZAMBOANGA CITY', '57');
INSERT INTO city (name, province_id) VALUES ('LAKEWOOD', '57');
INSERT INTO city (name, province_id) VALUES ('JOSEFINA', '57');
INSERT INTO city (name, province_id) VALUES ('SOMINOT (DON MARIANO MARCOS)', '57');
INSERT INTO city (name, province_id) VALUES ('VINCENZO A. SAGUN', '57');
INSERT INTO city (name, province_id) VALUES ('GUIPOS', '57');
INSERT INTO city (name, province_id) VALUES ('TIGBAO', '57');
INSERT INTO city (name, province_id) VALUES ('BUUG', '58');
INSERT INTO city (name, province_id) VALUES ('DIPLAHAN', '58');
INSERT INTO city (name, province_id) VALUES ('IMELDA', '58');
INSERT INTO city (name, province_id) VALUES ('IPIL (Capital)', '58');
INSERT INTO city (name, province_id) VALUES ('KABASALAN', '58');
INSERT INTO city (name, province_id) VALUES ('MABUHAY', '58');
INSERT INTO city (name, province_id) VALUES ('MALANGAS', '58');
INSERT INTO city (name, province_id) VALUES ('NAGA', '58');
INSERT INTO city (name, province_id) VALUES ('OLUTANGA', '58');
INSERT INTO city (name, province_id) VALUES ('PAYAO', '58');
INSERT INTO city (name, province_id) VALUES ('ROSELLER LIM', '58');
INSERT INTO city (name, province_id) VALUES ('SIAY', '58');
INSERT INTO city (name, province_id) VALUES ('TALUSAN', '58');
INSERT INTO city (name, province_id) VALUES ('TITAY', '58');
INSERT INTO city (name, province_id) VALUES ('TUNGAWAN', '58');
INSERT INTO city (name, province_id) VALUES ('CITY OF ISABELA (Capital)', '59');
INSERT INTO city (name, province_id) VALUES ('DAPITAN CITY', '56');
INSERT INTO city (name, province_id) VALUES ('DAMULOG', '60');
INSERT INTO city (name, province_id) VALUES ('DANGCAGAN', '60');
INSERT INTO city (name, province_id) VALUES ('DON CARLOS', '60');
INSERT INTO city (name, province_id) VALUES ('IMPASUG-ONG', '60');
INSERT INTO city (name, province_id) VALUES ('KADINGILAN', '60');
INSERT INTO city (name, province_id) VALUES ('KALILANGAN', '60');
INSERT INTO city (name, province_id) VALUES ('KIBAWE', '60');
INSERT INTO city (name, province_id) VALUES ('KITAOTAO', '60');
INSERT INTO city (name, province_id) VALUES ('LANTAPAN', '60');
INSERT INTO city (name, province_id) VALUES ('LIBONA', '60');
INSERT INTO city (name, province_id) VALUES ('CITY OF MALAYBALAY (Capital)', '60');
INSERT INTO city (name, province_id) VALUES ('MANOLO FORTICH', '60');
INSERT INTO city (name, province_id) VALUES ('MARAMAG', '60');
INSERT INTO city (name, province_id) VALUES ('PANGANTUCAN', '60');
INSERT INTO city (name, province_id) VALUES ('SUMILAO', '60');
INSERT INTO city (name, province_id) VALUES ('TALAKAG', '60');
INSERT INTO city (name, province_id) VALUES ('CITY OF VALENCIA', '60');
INSERT INTO city (name, province_id) VALUES ('CABANGLASAN', '60');
INSERT INTO city (name, province_id) VALUES ('GUINSILIBAN', '61');
INSERT INTO city (name, province_id) VALUES ('MAHINOG', '61');
INSERT INTO city (name, province_id) VALUES ('MAMBAJAO (Capital)', '61');
INSERT INTO city (name, province_id) VALUES ('SAGAY', '61');
INSERT INTO city (name, province_id) VALUES ('BALOI', '62');
INSERT INTO city (name, province_id) VALUES ('BAROY', '62');
INSERT INTO city (name, province_id) VALUES ('ILIGAN CITY', '62');
INSERT INTO city (name, province_id) VALUES ('KAPATAGAN', '62');
INSERT INTO city (name, province_id) VALUES ('SULTAN NAGA DIMAPORO (KAROMATAN)', '62');
INSERT INTO city (name, province_id) VALUES ('KAUSWAGAN', '62');
INSERT INTO city (name, province_id) VALUES ('KOLAMBUGAN', '62');
INSERT INTO city (name, province_id) VALUES ('LALA', '62');
INSERT INTO city (name, province_id) VALUES ('LINAMON', '62');
INSERT INTO city (name, province_id) VALUES ('MAIGO', '62');
INSERT INTO city (name, province_id) VALUES ('MATUNGAO', '62');
INSERT INTO city (name, province_id) VALUES ('MUNAI', '62');
INSERT INTO city (name, province_id) VALUES ('NUNUNGAN', '62');
INSERT INTO city (name, province_id) VALUES ('PANTAO RAGAT', '62');
INSERT INTO city (name, province_id) VALUES ('POONA PIAGAPO', '62');
INSERT INTO city (name, province_id) VALUES ('SALVADOR', '62');
INSERT INTO city (name, province_id) VALUES ('SAPAD', '62');
INSERT INTO city (name, province_id) VALUES ('TAGOLOAN', '62');
INSERT INTO city (name, province_id) VALUES ('TANGCAL', '62');
INSERT INTO city (name, province_id) VALUES ('TUBOD (Capital)', '62');
INSERT INTO city (name, province_id) VALUES ('PANTAR', '62');
INSERT INTO city (name, province_id) VALUES ('BALIANGAO', '63');
INSERT INTO city (name, province_id) VALUES ('BONIFACIO', '63');
INSERT INTO city (name, province_id) VALUES ('CALAMBA', '63');
INSERT INTO city (name, province_id) VALUES ('JIMENEZ', '63');
INSERT INTO city (name, province_id) VALUES ('LOPEZ JAENA', '63');
INSERT INTO city (name, province_id) VALUES ('OROQUIETA CITY (Capital)', '63');
INSERT INTO city (name, province_id) VALUES ('OZAMIS CITY', '63');
INSERT INTO city (name, province_id) VALUES ('PANAON', '63');
INSERT INTO city (name, province_id) VALUES ('SAPANG DALAGA', '63');
INSERT INTO city (name, province_id) VALUES ('SINACABAN', '63');
INSERT INTO city (name, province_id) VALUES ('TANGUB CITY', '63');
INSERT INTO city (name, province_id) VALUES ('DON VICTORIANO CHIONGBIAN  (DON MARIANO MARCOS)', '63');
INSERT INTO city (name, province_id) VALUES ('BALINGASAG', '64');
INSERT INTO city (name, province_id) VALUES ('BALINGOAN', '64');
INSERT INTO city (name, province_id) VALUES ('BINUANGAN', '64');
INSERT INTO city (name, province_id) VALUES ('CAGAYAN DE ORO CITY (Capital)', '64');
INSERT INTO city (name, province_id) VALUES ('CITY OF EL SALVADOR', '64');
INSERT INTO city (name, province_id) VALUES ('GINGOOG CITY', '64');
INSERT INTO city (name, province_id) VALUES ('GITAGUM', '64');
INSERT INTO city (name, province_id) VALUES ('INITAO', '64');
INSERT INTO city (name, province_id) VALUES ('JASAAN', '64');
INSERT INTO city (name, province_id) VALUES ('KINOGUITAN', '64');
INSERT INTO city (name, province_id) VALUES ('LAGONGLONG', '64');
INSERT INTO city (name, province_id) VALUES ('LAGUINDINGAN', '64');
INSERT INTO city (name, province_id) VALUES ('LUGAIT', '64');
INSERT INTO city (name, province_id) VALUES ('MAGSAYSAY (LINUGOS)', '64');
INSERT INTO city (name, province_id) VALUES ('MANTICAO', '64');
INSERT INTO city (name, province_id) VALUES ('MEDINA', '64');
INSERT INTO city (name, province_id) VALUES ('NAAWAN', '64');
INSERT INTO city (name, province_id) VALUES ('OPOL', '64');
INSERT INTO city (name, province_id) VALUES ('SALAY', '64');
INSERT INTO city (name, province_id) VALUES ('SUGBONGCOGON', '64');
INSERT INTO city (name, province_id) VALUES ('TALISAYAN', '64');
INSERT INTO city (name, province_id) VALUES ('VILLANUEVA', '64');
INSERT INTO city (name, province_id) VALUES ('BAUNGON', '60');
INSERT INTO city (name, province_id) VALUES ('CATARMAN', '61');
INSERT INTO city (name, province_id) VALUES ('BACOLOD', '62');
INSERT INTO city (name, province_id) VALUES ('ALORAN', '63');
INSERT INTO city (name, province_id) VALUES ('ALUBIJID', '64');
INSERT INTO city (name, province_id) VALUES ('LAAK (SAN VICENTE)', '65');
INSERT INTO city (name, province_id) VALUES ('MABINI (DOÑA ALICIA)', '65');
INSERT INTO city (name, province_id) VALUES ('MACO', '65');
INSERT INTO city (name, province_id) VALUES ('MARAGUSAN (SAN MARIANO)', '65');
INSERT INTO city (name, province_id) VALUES ('MAWAB', '65');
INSERT INTO city (name, province_id) VALUES ('MONKAYO', '65');
INSERT INTO city (name, province_id) VALUES ('MONTEVISTA', '65');
INSERT INTO city (name, province_id) VALUES ('NABUNTURAN (Capital)', '65');
INSERT INTO city (name, province_id) VALUES ('NEW BATAAN', '65');
INSERT INTO city (name, province_id) VALUES ('PANTUKAN', '65');
INSERT INTO city (name, province_id) VALUES ('KAPALONG', '66');
INSERT INTO city (name, province_id) VALUES ('NEW CORELLA', '66');
INSERT INTO city (name, province_id) VALUES ('CITY OF PANABO', '66');
INSERT INTO city (name, province_id) VALUES ('ISLAND GARDEN CITY OF SAMAL', '66');
INSERT INTO city (name, province_id) VALUES ('CITY OF TAGUM (Capital)', '66');
INSERT INTO city (name, province_id) VALUES ('TALAINGOD', '66');
INSERT INTO city (name, province_id) VALUES ('BRAULIO E. DUJALI', '66');
INSERT INTO city (name, province_id) VALUES ('DAVAO CITY', '67');
INSERT INTO city (name, province_id) VALUES ('CITY OF DIGOS (Capital)', '67');
INSERT INTO city (name, province_id) VALUES ('JOSE ABAD SANTOS (TRINIDAD)', '67');
INSERT INTO city (name, province_id) VALUES ('KIBLAWAN', '67');
INSERT INTO city (name, province_id) VALUES ('MALALAG', '67');
INSERT INTO city (name, province_id) VALUES ('MALITA', '67');
INSERT INTO city (name, province_id) VALUES ('MATANAO', '67');
INSERT INTO city (name, province_id) VALUES ('PADADA', '67');
INSERT INTO city (name, province_id) VALUES ('SULOP', '67');
INSERT INTO city (name, province_id) VALUES ('SARANGANI', '67');
INSERT INTO city (name, province_id) VALUES ('DON MARCELINO', '67');
INSERT INTO city (name, province_id) VALUES ('BANAYBANAY', '68');
INSERT INTO city (name, province_id) VALUES ('BOSTON', '68');
INSERT INTO city (name, province_id) VALUES ('CARAGA', '68');
INSERT INTO city (name, province_id) VALUES ('CATEEL', '68');
INSERT INTO city (name, province_id) VALUES ('GOVERNOR GENEROSO', '68');
INSERT INTO city (name, province_id) VALUES ('LUPON', '68');
INSERT INTO city (name, province_id) VALUES ('MANAY', '68');
INSERT INTO city (name, province_id) VALUES ('CITY OF MATI (Capital)', '68');
INSERT INTO city (name, province_id) VALUES ('TARRAGONA', '68');
INSERT INTO city (name, province_id) VALUES ('ASUNCION (SAUG)', '66');
INSERT INTO city (name, province_id) VALUES ('BANSALAN', '67');
INSERT INTO city (name, province_id) VALUES ('BAGANGA', '68');
INSERT INTO city (name, province_id) VALUES ('KABACAN', '69');
INSERT INTO city (name, province_id) VALUES ('CITY OF KIDAPAWAN (Capital)', '69');
INSERT INTO city (name, province_id) VALUES ('LIBUNGAN', '69');
INSERT INTO city (name, province_id) VALUES ('MAGPET', '69');
INSERT INTO city (name, province_id) VALUES ('MAKILALA', '69');
INSERT INTO city (name, province_id) VALUES ('MATALAM', '69');
INSERT INTO city (name, province_id) VALUES ('MIDSAYAP', '69');
INSERT INTO city (name, province_id) VALUES ('PIGKAWAYAN', '69');
INSERT INTO city (name, province_id) VALUES ('PIKIT', '69');
INSERT INTO city (name, province_id) VALUES ('TULUNAN', '69');
INSERT INTO city (name, province_id) VALUES ('ANTIPAS', '69');
INSERT INTO city (name, province_id) VALUES ('BANISILAN', '69');
INSERT INTO city (name, province_id) VALUES ('ALEOSAN', '69');
INSERT INTO city (name, province_id) VALUES ('ARAKAN', '69');
INSERT INTO city (name, province_id) VALUES ('GLAN', '70');
INSERT INTO city (name, province_id) VALUES ('KIAMBA', '70');
INSERT INTO city (name, province_id) VALUES ('MAASIM', '70');
INSERT INTO city (name, province_id) VALUES ('MAITUM', '70');
INSERT INTO city (name, province_id) VALUES ('MALAPATAN', '70');
INSERT INTO city (name, province_id) VALUES ('MALUNGON', '70');
INSERT INTO city (name, province_id) VALUES ('GENERAL SANTOS CITY (DADIANGAS)', '71');
INSERT INTO city (name, province_id) VALUES ('CITY OF KORONADAL (Capital)', '71');
INSERT INTO city (name, province_id) VALUES ('NORALA', '71');
INSERT INTO city (name, province_id) VALUES ('POLOMOLOK', '71');
INSERT INTO city (name, province_id) VALUES ('SURALLAH', '71');
INSERT INTO city (name, province_id) VALUES ('TAMPAKAN', '71');
INSERT INTO city (name, province_id) VALUES ('TANTANGAN', '71');
INSERT INTO city (name, province_id) VALUES ('TUPI', '71');
INSERT INTO city (name, province_id) VALUES ('LAKE SEBU', '71');
INSERT INTO city (name, province_id) VALUES ('COLUMBIO', '72');
INSERT INTO city (name, province_id) VALUES ('ISULAN (Capital)', '72');
INSERT INTO city (name, province_id) VALUES ('KALAMANSIG', '72');
INSERT INTO city (name, province_id) VALUES ('LEBAK', '72');
INSERT INTO city (name, province_id) VALUES ('LUTAYAN', '72');
INSERT INTO city (name, province_id) VALUES ('LAMBAYONG (MARIANO MARCOS)', '72');
INSERT INTO city (name, province_id) VALUES ('PALIMBANG', '72');
INSERT INTO city (name, province_id) VALUES ('PRESIDENT QUIRINO', '72');
INSERT INTO city (name, province_id) VALUES ('CITY OF TACURONG', '72');
INSERT INTO city (name, province_id) VALUES ('SEN. NINOY AQUINO', '72');
INSERT INTO city (name, province_id) VALUES ('ALAMADA', '69');
INSERT INTO city (name, province_id) VALUES ('COTABATO CITY', '73');
INSERT INTO city (name, province_id) VALUES ('ALABEL (Capital)', '70');
INSERT INTO city (name, province_id) VALUES ('BAGUMBAYAN', '72');
INSERT INTO city (name, province_id) VALUES ('BUTUAN CITY (Capital)', '74');
INSERT INTO city (name, province_id) VALUES ('CITY OF CABADBARAN', '74');
INSERT INTO city (name, province_id) VALUES ('JABONGA', '74');
INSERT INTO city (name, province_id) VALUES ('KITCHARAO', '74');
INSERT INTO city (name, province_id) VALUES ('LAS NIEVES', '74');
INSERT INTO city (name, province_id) VALUES ('NASIPIT', '74');
INSERT INTO city (name, province_id) VALUES ('TUBAY', '74');
INSERT INTO city (name, province_id) VALUES ('REMEDIOS T. ROMUALDEZ', '74');
INSERT INTO city (name, province_id) VALUES ('BUNAWAN', '75');
INSERT INTO city (name, province_id) VALUES ('LORETO', '75');
INSERT INTO city (name, province_id) VALUES ('PROSPERIDAD (Capital)', '75');
INSERT INTO city (name, province_id) VALUES ('SANTA JOSEFA', '75');
INSERT INTO city (name, province_id) VALUES ('TALACOGON', '75');
INSERT INTO city (name, province_id) VALUES ('TRENTO', '75');
INSERT INTO city (name, province_id) VALUES ('VERUELA', '75');
INSERT INTO city (name, province_id) VALUES ('SIBAGAT', '75');
INSERT INTO city (name, province_id) VALUES ('CAGDIANAO', '76');
INSERT INTO city (name, province_id) VALUES ('DINAGAT', '76');
INSERT INTO city (name, province_id) VALUES ('LIBJO (ALBOR)', '76');
INSERT INTO city (name, province_id) VALUES ('TUBAJON', '76');
INSERT INTO city (name, province_id) VALUES ('BACUAG', '77');
INSERT INTO city (name, province_id) VALUES ('CLAVER', '77');
INSERT INTO city (name, province_id) VALUES ('DAPA', '77');
INSERT INTO city (name, province_id) VALUES ('DEL CARMEN', '77');
INSERT INTO city (name, province_id) VALUES ('GIGAQUIT', '77');
INSERT INTO city (name, province_id) VALUES ('MAINIT', '77');
INSERT INTO city (name, province_id) VALUES ('MALIMONO', '77');
INSERT INTO city (name, province_id) VALUES ('SAN BENITO', '77');
INSERT INTO city (name, province_id) VALUES ('SAN FRANCISCO (ANAO-AON)', '77');
INSERT INTO city (name, province_id) VALUES ('SANTA MONICA (SAPAO)', '77');
INSERT INTO city (name, province_id) VALUES ('SURIGAO CITY (Capital)', '77');
INSERT INTO city (name, province_id) VALUES ('TAGANA-AN', '77');
INSERT INTO city (name, province_id) VALUES ('TUBOD', '77');
INSERT INTO city (name, province_id) VALUES ('BAYABAS', '78');
INSERT INTO city (name, province_id) VALUES ('CITY OF BISLIG', '78');
INSERT INTO city (name, province_id) VALUES ('CAGWAIT', '78');
INSERT INTO city (name, province_id) VALUES ('CANTILAN', '78');
INSERT INTO city (name, province_id) VALUES ('CARRASCAL', '78');
INSERT INTO city (name, province_id) VALUES ('HINATUAN', '78');
INSERT INTO city (name, province_id) VALUES ('LANUZA', '78');
INSERT INTO city (name, province_id) VALUES ('LIANGA', '78');
INSERT INTO city (name, province_id) VALUES ('LINGIG', '78');
INSERT INTO city (name, province_id) VALUES ('MADRID', '78');
INSERT INTO city (name, province_id) VALUES ('MARIHATAG', '78');
INSERT INTO city (name, province_id) VALUES ('TAGBINA', '78');
INSERT INTO city (name, province_id) VALUES ('TAGO', '78');
INSERT INTO city (name, province_id) VALUES ('CITY OF TANDAG (Capital)', '78');
INSERT INTO city (name, province_id) VALUES ('CITY OF BAYUGAN', '75');
INSERT INTO city (name, province_id) VALUES ('BASILISA (RIZAL)', '76');
INSERT INTO city (name, province_id) VALUES ('BAROBO', '78');
INSERT INTO city (name, province_id) VALUES ('LANTAWAN', '79');
INSERT INTO city (name, province_id) VALUES ('MALUSO', '79');
INSERT INTO city (name, province_id) VALUES ('SUMISIP', '79');
INSERT INTO city (name, province_id) VALUES ('TIPO-TIPO', '79');
INSERT INTO city (name, province_id) VALUES ('AKBAR', '79');
INSERT INTO city (name, province_id) VALUES ('AL-BARKA', '79');
INSERT INTO city (name, province_id) VALUES ('HADJI MOHAMMAD AJUL', '79');
INSERT INTO city (name, province_id) VALUES ('UNGKAYA PUKAN', '79');
INSERT INTO city (name, province_id) VALUES ('HADJI MUHTAMAD', '79');
INSERT INTO city (name, province_id) VALUES ('TABUAN-LASA', '79');
INSERT INTO city (name, province_id) VALUES ('BALABAGAN', '80');
INSERT INTO city (name, province_id) VALUES ('BALINDONG (WATU)', '80');
INSERT INTO city (name, province_id) VALUES ('BAYANG', '80');
INSERT INTO city (name, province_id) VALUES ('BINIDAYAN', '80');
INSERT INTO city (name, province_id) VALUES ('BUBONG', '80');
INSERT INTO city (name, province_id) VALUES ('BUTIG', '80');
INSERT INTO city (name, province_id) VALUES ('GANASSI', '80');
INSERT INTO city (name, province_id) VALUES ('KAPAI', '80');
INSERT INTO city (name, province_id) VALUES ('LUMBA-BAYABAO (MAGUING)', '80');
INSERT INTO city (name, province_id) VALUES ('LUMBATAN', '80');
INSERT INTO city (name, province_id) VALUES ('MADALUM', '80');
INSERT INTO city (name, province_id) VALUES ('MADAMBA', '80');
INSERT INTO city (name, province_id) VALUES ('MALABANG', '80');
INSERT INTO city (name, province_id) VALUES ('MARANTAO', '80');
INSERT INTO city (name, province_id) VALUES ('MARAWI CITY (Capital)', '80');
INSERT INTO city (name, province_id) VALUES ('MASIU', '80');
INSERT INTO city (name, province_id) VALUES ('MULONDO', '80');
INSERT INTO city (name, province_id) VALUES ('PAGAYAWAN (TATARIKAN)', '80');
INSERT INTO city (name, province_id) VALUES ('PIAGAPO', '80');
INSERT INTO city (name, province_id) VALUES ('POONA BAYABAO (GATA)', '80');
INSERT INTO city (name, province_id) VALUES ('PUALAS', '80');
INSERT INTO city (name, province_id) VALUES ('DITSAAN-RAMAIN', '80');
INSERT INTO city (name, province_id) VALUES ('SAGUIARAN', '80');
INSERT INTO city (name, province_id) VALUES ('TAMPARAN', '80');
INSERT INTO city (name, province_id) VALUES ('TARAKA', '80');
INSERT INTO city (name, province_id) VALUES ('TUBARAN', '80');
INSERT INTO city (name, province_id) VALUES ('TUGAYA', '80');
INSERT INTO city (name, province_id) VALUES ('WAO', '80');
INSERT INTO city (name, province_id) VALUES ('MAROGONG', '80');
INSERT INTO city (name, province_id) VALUES ('CALANOGAS', '80');
INSERT INTO city (name, province_id) VALUES ('BUADIPOSO-BUNTONG', '80');
INSERT INTO city (name, province_id) VALUES ('MAGUING', '80');
INSERT INTO city (name, province_id) VALUES ('PICONG (SULTAN GUMANDER)', '80');
INSERT INTO city (name, province_id) VALUES ('LUMBAYANAGUE', '80');
INSERT INTO city (name, province_id) VALUES ('BUMBARAN', '80');
INSERT INTO city (name, province_id) VALUES ('TAGOLOAN II', '80');
INSERT INTO city (name, province_id) VALUES ('SULTAN DUMALONDONG', '80');
INSERT INTO city (name, province_id) VALUES ('LUMBACA-UNAYAN', '80');
INSERT INTO city (name, province_id) VALUES ('BULDON', '81');
INSERT INTO city (name, province_id) VALUES ('BULUAN', '81');
INSERT INTO city (name, province_id) VALUES ('DATU PAGLAS', '81');
INSERT INTO city (name, province_id) VALUES ('DATU PIANG', '81');
INSERT INTO city (name, province_id) VALUES ('DATU ODIN SINSUAT (DINAIG)', '81');
INSERT INTO city (name, province_id) VALUES ('SHARIFF AGUAK (MAGANOY) (Capital)', '81');
INSERT INTO city (name, province_id) VALUES ('MATANOG', '81');
INSERT INTO city (name, province_id) VALUES ('PAGALUNGAN', '81');
INSERT INTO city (name, province_id) VALUES ('PARANG', '81');
INSERT INTO city (name, province_id) VALUES ('SULTAN KUDARAT (NULING)', '81');
INSERT INTO city (name, province_id) VALUES ('SULTAN SA BARONGIS (LAMBAYONG)', '81');
INSERT INTO city (name, province_id) VALUES ('KABUNTALAN (TUMBAO)', '81');
INSERT INTO city (name, province_id) VALUES ('UPI', '81');
INSERT INTO city (name, province_id) VALUES ('TALAYAN', '81');
INSERT INTO city (name, province_id) VALUES ('SOUTH UPI', '81');
INSERT INTO city (name, province_id) VALUES ('BARIRA', '81');
INSERT INTO city (name, province_id) VALUES ('GEN. S. K. PENDATUN', '81');
INSERT INTO city (name, province_id) VALUES ('MAMASAPANO', '81');
INSERT INTO city (name, province_id) VALUES ('TALITAY', '81');
INSERT INTO city (name, province_id) VALUES ('PAGAGAWAN', '81');
INSERT INTO city (name, province_id) VALUES ('PAGLAT', '81');
INSERT INTO city (name, province_id) VALUES ('SULTAN MASTURA', '81');
INSERT INTO city (name, province_id) VALUES ('GUINDULUNGAN', '81');
INSERT INTO city (name, province_id) VALUES ('DATU SAUDI-AMPATUAN', '81');
INSERT INTO city (name, province_id) VALUES ('DATU UNSAY', '81');
INSERT INTO city (name, province_id) VALUES ('DATU ABDULLAH SANGKI', '81');
INSERT INTO city (name, province_id) VALUES ('RAJAH BUAYAN', '81');
INSERT INTO city (name, province_id) VALUES ('DATU BLAH T. SINSUAT', '81');
INSERT INTO city (name, province_id) VALUES ('DATU ANGGAL MIDTIMBANG', '81');
INSERT INTO city (name, province_id) VALUES ('MANGUDADATU', '81');
INSERT INTO city (name, province_id) VALUES ('PANDAG', '81');
INSERT INTO city (name, province_id) VALUES ('NORTHERN KABUNTALAN', '81');
INSERT INTO city (name, province_id) VALUES ('DATU HOFFER AMPATUAN', '81');
INSERT INTO city (name, province_id) VALUES ('DATU SALIBO', '81');
INSERT INTO city (name, province_id) VALUES ('SHARIFF SAYDONA MUSTAPHA', '81');
INSERT INTO city (name, province_id) VALUES ('JOLO (Capital)', '82');
INSERT INTO city (name, province_id) VALUES ('KALINGALAN CALUANG', '82');
INSERT INTO city (name, province_id) VALUES ('LUUK', '82');
INSERT INTO city (name, province_id) VALUES ('MAIMBUNG', '82');
INSERT INTO city (name, province_id) VALUES ('HADJI PANGLIMA TAHIL (MARUNGGAS)', '82');
INSERT INTO city (name, province_id) VALUES ('OLD PANAMAO', '82');
INSERT INTO city (name, province_id) VALUES ('PANGUTARAN', '82');
INSERT INTO city (name, province_id) VALUES ('PATA', '82');
INSERT INTO city (name, province_id) VALUES ('PATIKUL', '82');
INSERT INTO city (name, province_id) VALUES ('SIASI', '82');
INSERT INTO city (name, province_id) VALUES ('TALIPAO', '82');
INSERT INTO city (name, province_id) VALUES ('TAPUL', '82');
INSERT INTO city (name, province_id) VALUES ('TONGKIL', '82');
INSERT INTO city (name, province_id) VALUES ('PANGLIMA ESTINO (NEW PANAMAO)', '82');
INSERT INTO city (name, province_id) VALUES ('LUGUS', '82');
INSERT INTO city (name, province_id) VALUES ('PANDAMI', '82');
INSERT INTO city (name, province_id) VALUES ('OMAR', '82');
INSERT INTO city (name, province_id) VALUES ('BONGAO (Capital)', '83');
INSERT INTO city (name, province_id) VALUES ('MAPUN (CAGAYAN DE TAWI-TAWI)', '83');
INSERT INTO city (name, province_id) VALUES ('SIMUNUL', '83');
INSERT INTO city (name, province_id) VALUES ('SITANGKAI', '83');
INSERT INTO city (name, province_id) VALUES ('SOUTH UBIAN', '83');
INSERT INTO city (name, province_id) VALUES ('TANDUBAS', '83');
INSERT INTO city (name, province_id) VALUES ('TURTLE ISLANDS', '83');
INSERT INTO city (name, province_id) VALUES ('LANGUYAN', '83');
INSERT INTO city (name, province_id) VALUES ('SAPA-SAPA', '83');
INSERT INTO city (name, province_id) VALUES ('SIBUTU', '83');
INSERT INTO city (name, province_id) VALUES ('CITY OF LAMITAN', '79');
INSERT INTO city (name, province_id) VALUES ('BACOLOD-KALAWI (BACOLOD GRANDE)', '80');
INSERT INTO city (name, province_id) VALUES ('AMPATUAN', '81');
INSERT INTO city (name, province_id) VALUES ('INDANAN', '82');
INSERT INTO city (name, province_id) VALUES ('PANGLIMA SUGALA (BALIMBING) (Capital)', '83');
