INSERT INTO province (name, region_id) VALUES ('METRO MANILA', '4');
INSERT INTO province (name, region_id) VALUES ('ABRA', '8');
INSERT INTO province (name, region_id) VALUES ('APAYAO', '8');
INSERT INTO province (name, region_id) VALUES ('BENGUET', '8');
INSERT INTO province (name, region_id) VALUES ('IFUGAO', '8');
INSERT INTO province (name, region_id) VALUES ('KALINGA', '8');
INSERT INTO province (name, region_id) VALUES ('MOUNTAIN PROVINCE', '8');
INSERT INTO province (name, region_id) VALUES ('ILOCOS NORTE', '5');
INSERT INTO province (name, region_id) VALUES ('ILOCOS SUR', '5');
INSERT INTO province (name, region_id) VALUES ('LA UNION', '5');
INSERT INTO province (name, region_id) VALUES ('PANGASINAN', '5');
INSERT INTO province (name, region_id) VALUES ('BATANES', '18');
INSERT INTO province (name, region_id) VALUES ('CAGAYAN', '18');
INSERT INTO province (name, region_id) VALUES ('ISABELA', '18');
INSERT INTO province (name, region_id) VALUES ('NUEVA VIZCAYA', '18');
INSERT INTO province (name, region_id) VALUES ('QUIRINO', '18');
INSERT INTO province (name, region_id) VALUES ('AURORA', '15');
INSERT INTO province (name, region_id) VALUES ('BATAAN', '15');
INSERT INTO province (name, region_id) VALUES ('BULACAN', '15');
INSERT INTO province (name, region_id) VALUES ('NUEVA ECIJA', '15');
INSERT INTO province (name, region_id) VALUES ('PAMPANGA', '15');
INSERT INTO province (name, region_id) VALUES ('TARLAC', '15');
INSERT INTO province (name, region_id) VALUES ('ZAMBALES', '15');
INSERT INTO province (name, region_id) VALUES ('BATANGAS', '2');
INSERT INTO province (name, region_id) VALUES ('CAVITE', '2');
INSERT INTO province (name, region_id) VALUES ('LAGUNA', '2');
INSERT INTO province (name, region_id) VALUES ('QUEZON', '2');
INSERT INTO province (name, region_id) VALUES ('RIZAL', '2');
INSERT INTO province (name, region_id) VALUES ('MARINDUQUE', '7');
INSERT INTO province (name, region_id) VALUES ('OCCIDENTAL MINDORO', '7');
INSERT INTO province (name, region_id) VALUES ('ORIENTAL MINDORO', '7');
INSERT INTO province (name, region_id) VALUES ('PALAWAN', '7');
INSERT INTO province (name, region_id) VALUES ('ROMBLON', '7');
INSERT INTO province (name, region_id) VALUES ('ALBAY', '3');
INSERT INTO province (name, region_id) VALUES ('CAMARINES NORTE', '3');
INSERT INTO province (name, region_id) VALUES ('CAMARINES SUR', '3');
INSERT INTO province (name, region_id) VALUES ('CATANDUANES', '3');
INSERT INTO province (name, region_id) VALUES ('MASBATE', '3');
INSERT INTO province (name, region_id) VALUES ('SORSOGON', '3');
INSERT INTO province (name, region_id) VALUES ('AKLAN', '10');
INSERT INTO province (name, region_id) VALUES ('ANTIQUE', '10');
INSERT INTO province (name, region_id) VALUES ('CAPIZ', '10');
INSERT INTO province (name, region_id) VALUES ('GUIMARAS', '10');
INSERT INTO province (name, region_id) VALUES ('ILOILO', '10');
INSERT INTO province (name, region_id) VALUES ('NEGROS OCCIDENTAL', '10');
INSERT INTO province (name, region_id) VALUES ('BOHOL', '9');
INSERT INTO province (name, region_id) VALUES ('CEBU', '9');
INSERT INTO province (name, region_id) VALUES ('NEGROS ORIENTAL', '9');
INSERT INTO province (name, region_id) VALUES ('SIQUIJOR', '9');
INSERT INTO province (name, region_id) VALUES ('BILIRAN', '6');
INSERT INTO province (name, region_id) VALUES ('EASTERN SAMAR', '6');
INSERT INTO province (name, region_id) VALUES ('LEYTE', '6');
INSERT INTO province (name, region_id) VALUES ('NORTHERN SAMAR', '6');
INSERT INTO province (name, region_id) VALUES ('SAMAR (WESTERN SAMAR)', '6');
INSERT INTO province (name, region_id) VALUES ('SOUTHERN LEYTE', '6');
INSERT INTO province (name, region_id) VALUES ('ZAMBOANGA DEL NORTE', '12');
INSERT INTO province (name, region_id) VALUES ('ZAMBOANGA DEL SUR', '12');
INSERT INTO province (name, region_id) VALUES ('ZAMBOANGA SIBUGAY', '12');
INSERT INTO province (name, region_id) VALUES ('CITY OF ISABELA (Not a Province)', '12');
INSERT INTO province (name, region_id) VALUES ('BUKIDNON', '17');
INSERT INTO province (name, region_id) VALUES ('CAMIGUIN', '17');
INSERT INTO province (name, region_id) VALUES ('LANAO DEL NORTE', '17');
INSERT INTO province (name, region_id) VALUES ('MISAMIS OCCIDENTAL', '17');
INSERT INTO province (name, region_id) VALUES ('MISAMIS ORIENTAL', '17');
INSERT INTO province (name, region_id) VALUES ('COMPOSTELA VALLEY', '11');
INSERT INTO province (name, region_id) VALUES ('DAVAO DEL NORTE', '11');
INSERT INTO province (name, region_id) VALUES ('DAVAO DEL SUR', '11');
INSERT INTO province (name, region_id) VALUES ('DAVAO ORIENTAL', '11');
INSERT INTO province (name, region_id) VALUES ('COTABATO (NORTH COTABATO)', '13');
INSERT INTO province (name, region_id) VALUES ('SARANGANI', '13');
INSERT INTO province (name, region_id) VALUES ('SOUTH COTABATO', '13');
INSERT INTO province (name, region_id) VALUES ('SULTAN KUDARAT', '13');
INSERT INTO province (name, region_id) VALUES ('COTABATO CITY (Not a Province)', '13');
INSERT INTO province (name, region_id) VALUES ('AGUSAN DEL NORTE', '14');
INSERT INTO province (name, region_id) VALUES ('AGUSAN DEL SUR', '14');
INSERT INTO province (name, region_id) VALUES ('DINAGAT ISLANDS', '14');
INSERT INTO province (name, region_id) VALUES ('SURIGAO DEL NORTE', '14');
INSERT INTO province (name, region_id) VALUES ('SURIGAO DEL SUR', '14');
INSERT INTO province (name, region_id) VALUES ('BASILAN', '16');
INSERT INTO province (name, region_id) VALUES ('LANAO DEL SUR', '16');
INSERT INTO province (name, region_id) VALUES ('MAGUINDANAO', '16');
INSERT INTO province (name, region_id) VALUES ('SULU', '16');
INSERT INTO province (name, region_id) VALUES ('TAWI-TAWI', '16');
