INSERT INTO region (name) VALUES ('REGION IV-A (CALABARZON)');
INSERT INTO region (name) VALUES ('REGION V (Bicol Region)');
INSERT INTO region (name) VALUES ('NCR - National Capital Region');
INSERT INTO region (name) VALUES ('REGION I (Ilocos Region)');
INSERT INTO region (name) VALUES ('REGION VIII (Eastern Visayas)');
INSERT INTO region (name) VALUES ('REGION IV-B (MIMAROPA)');
INSERT INTO region (name) VALUES ('CAR - Cordillera Administrative Region');
INSERT INTO region (name) VALUES ('REGION VII (Central Visayas)');
INSERT INTO region (name) VALUES ('REGION VI (Western Visayas)');
INSERT INTO region (name) VALUES ('REGION XI (Davao Region)');
INSERT INTO region (name) VALUES ('REGION IX (Zamboanga Peninsula)');
INSERT INTO region (name) VALUES ('REGION XII (Soccsksargen)');
INSERT INTO region (name) VALUES ('REGION XIII (Caraga)');
INSERT INTO region (name) VALUES ('REGION III (Central Luzon)');
INSERT INTO region (name) VALUES ('ARMM - Autonomous Region in Muslim Mindanao');
INSERT INTO region (name) VALUES ('REGION X (Northern Mindanao)');
INSERT INTO region (name) VALUES ('REGION II (Cagayan Valley)');
